// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct bool3
    {

        public static bool operator ==(bool3 left, bool3 right)
        {
            return left.x == right.x && left.y == right.y && left.z == right.z;
        }

        public static bool operator !=(bool3 left, bool3 right)
        {
            return left.x != right.x || left.y != right.y || left.z != right.z;
        }

        public static bool3 operator ^(bool3 left, bool3 right)
        {
            return new(left.x ^ right.x, left.y ^ right.y, left.z ^ right.z);
        }

        public static bool3 operator ^(bool3 left, bool right)
        {
            return new(left.x ^ right, left.y ^ right, left.z ^ right);
        }

        public static bool3 operator ^(bool left, bool3 right)
        {
            return new(left ^ right.x, left ^ right.y, left ^ right.z);
        }

        public static bool3 operator |(bool3 left, bool3 right)
        {
            return new(left.x | right.x, left.y | right.y, left.z | right.z);
        }

        public static bool3 operator |(bool3 left, bool right)
        {
            return new(left.x | right, left.y | right, left.z | right);
        }

        public static bool3 operator |(bool left, bool3 right)
        {
            return new(left | right.x, left | right.y, left | right.z);
        }

        public static bool3 operator &(bool3 left, bool3 right)
        {
            return new(left.x & right.x, left.y & right.y, left.z & right.z);
        }

        public static bool3 operator &(bool3 left, bool right)
        {
            return new(left.x & right, left.y & right, left.z & right);
        }

        public static bool3 operator &(bool left, bool3 right)
        {
            return new(left & right.x, left & right.y, left & right.z);
        }

        public static bool3 operator !(bool3 value)
        {
            return new(!value.x, !value.y, !value.z);
        }
    }
}
