// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct bool2
    {

        public static bool Any(bool2 value)
        {
            return value.x || value.y;
        }

        public static bool All(bool2 value)
        {
            return value.x && value.y;
        }

        public static bool2 Select(bool2 falseValue, bool2 trueValue, bool2 mask)
        {
            return new(mask.x ? trueValue.x : falseValue.x, mask.y ? trueValue.y : falseValue.y);
        }

        public static bool2 Select(bool2 falseValue, bool2 trueValue, bool mask)
        {
            return new(mask ? trueValue.x : falseValue.x, mask ? trueValue.y : falseValue.y);
        }

        public static bool2 Select(bool falseValue, bool trueValue, bool2 mask)
        {
            return new(mask.x ? trueValue : falseValue, mask.y ? trueValue : falseValue);
        }

        public static bool2 Equal(bool2 a, bool2 b)
        {
            return new(a.x == b.x, a.y == b.y);
        }

        public static bool2 Equal(bool2 a, bool b)
        {
            return new(a.x == b, a.y == b);
        }

        public static bool2 Equal(bool a, bool2 b)
        {
            return new(a == b.x, a == b.y);
        }

        public static bool2 NotEqual(bool2 a, bool2 b)
        {
            return new(a.x != b.x, a.y != b.y);
        }

        public static bool2 NotEqual(bool2 a, bool b)
        {
            return new(a.x != b, a.y != b);
        }

        public static bool2 NotEqual(bool a, bool2 b)
        {
            return new(a != b.x, a != b.y);
        }
    }
}
