// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct bool4
    {

        public static bool operator ==(bool4 left, bool4 right)
        {
            return left.x == right.x && left.y == right.y && left.z == right.z && left.w == right.w;
        }

        public static bool operator !=(bool4 left, bool4 right)
        {
            return left.x != right.x || left.y != right.y || left.z != right.z || left.w != right.w;
        }

        public static bool4 operator ^(bool4 left, bool4 right)
        {
            return new(left.x ^ right.x, left.y ^ right.y, left.z ^ right.z, left.w ^ right.w);
        }

        public static bool4 operator ^(bool4 left, bool right)
        {
            return new(left.x ^ right, left.y ^ right, left.z ^ right, left.w ^ right);
        }

        public static bool4 operator ^(bool left, bool4 right)
        {
            return new(left ^ right.x, left ^ right.y, left ^ right.z, left ^ right.w);
        }

        public static bool4 operator |(bool4 left, bool4 right)
        {
            return new(left.x | right.x, left.y | right.y, left.z | right.z, left.w | right.w);
        }

        public static bool4 operator |(bool4 left, bool right)
        {
            return new(left.x | right, left.y | right, left.z | right, left.w | right);
        }

        public static bool4 operator |(bool left, bool4 right)
        {
            return new(left | right.x, left | right.y, left | right.z, left | right.w);
        }

        public static bool4 operator &(bool4 left, bool4 right)
        {
            return new(left.x & right.x, left.y & right.y, left.z & right.z, left.w & right.w);
        }

        public static bool4 operator &(bool4 left, bool right)
        {
            return new(left.x & right, left.y & right, left.z & right, left.w & right);
        }

        public static bool4 operator &(bool left, bool4 right)
        {
            return new(left & right.x, left & right.y, left & right.z, left & right.w);
        }

        public static bool4 operator !(bool4 value)
        {
            return new(!value.x, !value.y, !value.z, !value.w);
        }
    }
}
