// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct bool3
    {

        public static bool Any(bool3 value)
        {
            return value.x || value.y || value.z;
        }

        public static bool All(bool3 value)
        {
            return value.x && value.y && value.z;
        }

        public static bool3 Select(bool3 falseValue, bool3 trueValue, bool3 mask)
        {
            return new(mask.x ? trueValue.x : falseValue.x, mask.y ? trueValue.y : falseValue.y, mask.z ? trueValue.z : falseValue.z);
        }

        public static bool3 Select(bool3 falseValue, bool3 trueValue, bool mask)
        {
            return new(mask ? trueValue.x : falseValue.x, mask ? trueValue.y : falseValue.y, mask ? trueValue.z : falseValue.z);
        }

        public static bool3 Select(bool falseValue, bool trueValue, bool3 mask)
        {
            return new(mask.x ? trueValue : falseValue, mask.y ? trueValue : falseValue, mask.z ? trueValue : falseValue);
        }

        public static bool3 Equal(bool3 a, bool3 b)
        {
            return new(a.x == b.x, a.y == b.y, a.z == b.z);
        }

        public static bool3 Equal(bool3 a, bool b)
        {
            return new(a.x == b, a.y == b, a.z == b);
        }

        public static bool3 Equal(bool a, bool3 b)
        {
            return new(a == b.x, a == b.y, a == b.z);
        }

        public static bool3 NotEqual(bool3 a, bool3 b)
        {
            return new(a.x != b.x, a.y != b.y, a.z != b.z);
        }

        public static bool3 NotEqual(bool3 a, bool b)
        {
            return new(a.x != b, a.y != b, a.z != b);
        }

        public static bool3 NotEqual(bool a, bool3 b)
        {
            return new(a != b.x, a != b.y, a != b.z);
        }
    }
}
