// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct bool2
    {

        public static bool operator ==(bool2 left, bool2 right)
        {
            return left.x == right.x && left.y == right.y;
        }

        public static bool operator !=(bool2 left, bool2 right)
        {
            return left.x != right.x || left.y != right.y;
        }

        public static bool2 operator ^(bool2 left, bool2 right)
        {
            return new(left.x ^ right.x, left.y ^ right.y);
        }

        public static bool2 operator ^(bool2 left, bool right)
        {
            return new(left.x ^ right, left.y ^ right);
        }

        public static bool2 operator ^(bool left, bool2 right)
        {
            return new(left ^ right.x, left ^ right.y);
        }

        public static bool2 operator |(bool2 left, bool2 right)
        {
            return new(left.x | right.x, left.y | right.y);
        }

        public static bool2 operator |(bool2 left, bool right)
        {
            return new(left.x | right, left.y | right);
        }

        public static bool2 operator |(bool left, bool2 right)
        {
            return new(left | right.x, left | right.y);
        }

        public static bool2 operator &(bool2 left, bool2 right)
        {
            return new(left.x & right.x, left.y & right.y);
        }

        public static bool2 operator &(bool2 left, bool right)
        {
            return new(left.x & right, left.y & right);
        }

        public static bool2 operator &(bool left, bool2 right)
        {
            return new(left & right.x, left & right.y);
        }

        public static bool2 operator !(bool2 value)
        {
            return new(!value.x, !value.y);
        }
    }
}
