// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace DVG.Maths
{
    public partial struct bool4
    {

        public static bool Any(bool4 value)
        {
            return value.x || value.y || value.z || value.w;
        }

        public static bool All(bool4 value)
        {
            return value.x && value.y && value.z && value.w;
        }

        public static bool4 Select(bool4 falseValue, bool4 trueValue, bool4 mask)
        {
            return new(mask.x ? trueValue.x : falseValue.x, mask.y ? trueValue.y : falseValue.y, mask.z ? trueValue.z : falseValue.z, mask.w ? trueValue.w : falseValue.w);
        }

        public static bool4 Select(bool4 falseValue, bool4 trueValue, bool mask)
        {
            return new(mask ? trueValue.x : falseValue.x, mask ? trueValue.y : falseValue.y, mask ? trueValue.z : falseValue.z, mask ? trueValue.w : falseValue.w);
        }

        public static bool4 Select(bool falseValue, bool trueValue, bool4 mask)
        {
            return new(mask.x ? trueValue : falseValue, mask.y ? trueValue : falseValue, mask.z ? trueValue : falseValue, mask.w ? trueValue : falseValue);
        }

        public static bool4 Equal(bool4 a, bool4 b)
        {
            return new(a.x == b.x, a.y == b.y, a.z == b.z, a.w == b.w);
        }

        public static bool4 Equal(bool4 a, bool b)
        {
            return new(a.x == b, a.y == b, a.z == b, a.w == b);
        }

        public static bool4 Equal(bool a, bool4 b)
        {
            return new(a == b.x, a == b.y, a == b.z, a == b.w);
        }

        public static bool4 NotEqual(bool4 a, bool4 b)
        {
            return new(a.x != b.x, a.y != b.y, a.z != b.z, a.w != b.w);
        }

        public static bool4 NotEqual(bool4 a, bool b)
        {
            return new(a.x != b, a.y != b, a.z != b, a.w != b);
        }

        public static bool4 NotEqual(bool a, bool4 b)
        {
            return new(a != b.x, a != b.y, a != b.z, a != b.w);
        }
    }
}
