// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace DVG.Maths
{
    public partial struct double4
    {

        public static double4 Select(double4 falseValue, double4 trueValue, bool4 mask)
        {
            return new(mask.x ? trueValue.x : falseValue.x, mask.y ? trueValue.y : falseValue.y, mask.z ? trueValue.z : falseValue.z, mask.w ? trueValue.w : falseValue.w);
        }

        public static double4 Select(double4 falseValue, double4 trueValue, bool mask)
        {
            return new(mask ? trueValue.x : falseValue.x, mask ? trueValue.y : falseValue.y, mask ? trueValue.z : falseValue.z, mask ? trueValue.w : falseValue.w);
        }

        public static double4 Select(double falseValue, double trueValue, bool4 mask)
        {
            return new(mask.x ? trueValue : falseValue, mask.y ? trueValue : falseValue, mask.z ? trueValue : falseValue, mask.w ? trueValue : falseValue);
        }

        public static bool4 Equal(double4 a, double4 b)
        {
            return new(a.x == b.x, a.y == b.y, a.z == b.z, a.w == b.w);
        }

        public static bool4 Equal(double4 a, double b)
        {
            return new(a.x == b, a.y == b, a.z == b, a.w == b);
        }

        public static bool4 Equal(double a, double4 b)
        {
            return new(a == b.x, a == b.y, a == b.z, a == b.w);
        }

        public static bool4 NotEqual(double4 a, double4 b)
        {
            return new(a.x != b.x, a.y != b.y, a.z != b.z, a.w != b.w);
        }

        public static bool4 NotEqual(double4 a, double b)
        {
            return new(a.x != b, a.y != b, a.z != b, a.w != b);
        }

        public static bool4 NotEqual(double a, double4 b)
        {
            return new(a != b.x, a != b.y, a != b.z, a != b.w);
        }

        public static bool4 LessThan(double4 a, double4 b)
        {
            return new(a.x < b.x, a.y < b.y, a.z < b.z, a.w < b.w);
        }

        public static bool4 LessThan(double4 a, double b)
        {
            return new(a.x < b, a.y < b, a.z < b, a.w < b);
        }

        public static bool4 LessThan(double a, double4 b)
        {
            return new(a < b.x, a < b.y, a < b.z, a < b.w);
        }

        public static bool4 LessThanOrEqual(double4 a, double4 b)
        {
            return new(a.x <= b.x, a.y <= b.y, a.z <= b.z, a.w <= b.w);
        }

        public static bool4 LessThanOrEqual(double4 a, double b)
        {
            return new(a.x <= b, a.y <= b, a.z <= b, a.w <= b);
        }

        public static bool4 LessThanOrEqual(double a, double4 b)
        {
            return new(a <= b.x, a <= b.y, a <= b.z, a <= b.w);
        }

        public static bool4 GreaterThan(double4 a, double4 b)
        {
            return new(a.x > b.x, a.y > b.y, a.z > b.z, a.w > b.w);
        }

        public static bool4 GreaterThan(double4 a, double b)
        {
            return new(a.x > b, a.y > b, a.z > b, a.w > b);
        }

        public static bool4 GreaterThan(double a, double4 b)
        {
            return new(a > b.x, a > b.y, a > b.z, a > b.w);
        }

        public static bool4 GreaterThanOrEqual(double4 a, double4 b)
        {
            return new(a.x >= b.x, a.y >= b.y, a.z >= b.z, a.w >= b.w);
        }

        public static bool4 GreaterThanOrEqual(double4 a, double b)
        {
            return new(a.x >= b, a.y >= b, a.z >= b, a.w >= b);
        }

        public static bool4 GreaterThanOrEqual(double a, double4 b)
        {
            return new(a >= b.x, a >= b.y, a >= b.z, a >= b.w);
        }

        public static bool4 IsNaN(double4 value)
        {
            return new(Maths.IsNaN(value.x), Maths.IsNaN(value.y), Maths.IsNaN(value.z), Maths.IsNaN(value.w));
        }

        public static bool4 IsInfinity(double4 value)
        {
            return new(Maths.IsInfinity(value.x), Maths.IsInfinity(value.y), Maths.IsInfinity(value.z), Maths.IsInfinity(value.w));
        }

        public static bool4 IsFinite(double4 value)
        {
            return new(Maths.IsFinite(value.x), Maths.IsFinite(value.y), Maths.IsFinite(value.z), Maths.IsFinite(value.w));
        }
    }
}
