// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct double3
    {

        public static bool operator ==(double3 left, double3 right)
        {
            return left.x == right.x && left.y == right.y && left.z == right.z;
        }

        public static bool operator !=(double3 left, double3 right)
        {
            return left.x != right.x || left.y != right.y || left.z != right.z;
        }

        public static double3 operator +(double3 value)
        {
            return new(+value.x, +value.y, +value.z);
        }

        public static double3 operator -(double3 value)
        {
            return new(-value.x, -value.y, -value.z);
        }

        public static double3 operator ++(double3 value)
        {
            return new(++value.x, ++value.y, ++value.z);
        }

        public static double3 operator --(double3 value)
        {
            return new(--value.x, --value.y, --value.z);
        }

        public static double3 operator +(double3 left, double3 right)
        {
            return new(left.x + right.x, left.y + right.y, left.z + right.z);
        }

        public static double3 operator -(double3 left, double3 right)
        {
            return new(left.x - right.x, left.y - right.y, left.z - right.z);
        }

        public static double3 operator *(double3 left, double3 right)
        {
            return new(left.x * right.x, left.y * right.y, left.z * right.z);
        }

        public static double3 operator /(double3 left, double3 right)
        {
            return new(left.x / right.x, left.y / right.y, left.z / right.z);
        }

        public static double3 operator +(double3 left, double right)
        {
            return new(left.x + right, left.y + right, left.z + right);
        }

        public static double3 operator +(double left, double3 right)
        {
            return new(left + right.x, left + right.y, left + right.z);
        }

        public static double3 operator -(double3 left, double right)
        {
            return new(left.x - right, left.y - right, left.z - right);
        }

        public static double3 operator -(double left, double3 right)
        {
            return new(left - right.x, left - right.y, left - right.z);
        }

        public static double3 operator *(double3 left, double right)
        {
            return new(left.x * right, left.y * right, left.z * right);
        }

        public static double3 operator *(double left, double3 right)
        {
            return new(left * right.x, left * right.y, left * right.z);
        }

        public static double3 operator /(double3 left, double right)
        {
            return new(left.x / right, left.y / right, left.z / right);
        }

        public static double3 operator /(double left, double3 right)
        {
            return new(left / right.x, left / right.y, left / right.z);
        }

        public static double3 operator %(double3 left, double3 right)
        {
            return new(left.x % right.x, left.y % right.y, left.z % right.z);
        }

        public static double3 operator %(double3 left, double right)
        {
            return new(left.x % right, left.y % right, left.z % right);
        }

        public static double3 operator %(double left, double3 right)
        {
            return new(left % right.x, left % right.y, left % right.z);
        }

        public static bool3 operator <(double3 left, double3 right)
        {
            return new(left.x < right.x, left.y < right.y, left.z < right.z);
        }

        public static bool3 operator <(double3 left, double right)
        {
            return new(left.x < right, left.y < right, left.z < right);
        }

        public static bool3 operator <(double left, double3 right)
        {
            return new(left < right.x, left < right.y, left < right.z);
        }

        public static bool3 operator <=(double3 left, double3 right)
        {
            return new(left.x <= right.x, left.y <= right.y, left.z <= right.z);
        }

        public static bool3 operator <=(double3 left, double right)
        {
            return new(left.x <= right, left.y <= right, left.z <= right);
        }

        public static bool3 operator <=(double left, double3 right)
        {
            return new(left <= right.x, left <= right.y, left <= right.z);
        }

        public static bool3 operator >(double3 left, double3 right)
        {
            return new(left.x > right.x, left.y > right.y, left.z > right.z);
        }

        public static bool3 operator >(double3 left, double right)
        {
            return new(left.x > right, left.y > right, left.z > right);
        }

        public static bool3 operator >(double left, double3 right)
        {
            return new(left > right.x, left > right.y, left > right.z);
        }

        public static bool3 operator >=(double3 left, double3 right)
        {
            return new(left.x >= right.x, left.y >= right.y, left.z >= right.z);
        }

        public static bool3 operator >=(double3 left, double right)
        {
            return new(left.x >= right, left.y >= right, left.z >= right);
        }

        public static bool3 operator >=(double left, double3 right)
        {
            return new(left >= right.x, left >= right.y, left >= right.z);
        }

        public static explicit operator int3(double3 value)
        {
            return new int3((int)value.x, (int)value.y, (int)value.z);
        }

        public static explicit operator uint3(double3 value)
        {
            return new uint3((uint)value.x, (uint)value.y, (uint)value.z);
        }

        public static explicit operator float3(double3 value)
        {
            return new float3((float)value.x, (float)value.y, (float)value.z);
        }

        public static explicit operator fix3(double3 value)
        {
            return new fix3((fix)value.x, (fix)value.y, (fix)value.z);
        }
    }
}
