// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct double2
    {

        public static double2 Min(double2 a, double2 b)
        {
            return new(Maths.Min(a.x, b.x), Maths.Min(a.y, b.y));
        }

        public static double2 Min(double2 a, double b)
        {
            return new(Maths.Min(a.x, b), Maths.Min(a.y, b));
        }

        public static double2 Min(double a, double2 b)
        {
            return new(Maths.Min(a, b.x), Maths.Min(a, b.y));
        }

        public static double2 Max(double2 a, double2 b)
        {
            return new(Maths.Max(a.x, b.x), Maths.Max(a.y, b.y));
        }

        public static double2 Max(double2 a, double b)
        {
            return new(Maths.Max(a.x, b), Maths.Max(a.y, b));
        }

        public static double2 Max(double a, double2 b)
        {
            return new(Maths.Max(a, b.x), Maths.Max(a, b.y));
        }

        public static double2 Clamp(double2 value, double min, double max)
        {
            return new(Maths.Clamp(value.x, min, max), Maths.Clamp(value.y, min, max));
        }

        public static double2 Clamp(double2 value, double2 min, double2 max)
        {
            return new(Maths.Clamp(value.x, min.x, max.x), Maths.Clamp(value.y, min.y, max.y));
        }

        public static double2 Abs(double2 value)
        {
            return new(Maths.Abs(value.x), Maths.Abs(value.y));
        }

        public static double2 Sign(double2 value)
        {
            return new(Maths.Sign(value.x), Maths.Sign(value.y));
        }

        public static double Sum(double2 value)
        {
            return value.x + value.y;
        }

        public static double2 Lerp(double2 a, double2 b, double t)
        {
            return new(Maths.Lerp(a.x, b.x, t), Maths.Lerp(a.y, b.y, t));
        }

        public static double2 Lerp(double2 a, double2 b, double2 t)
        {
            return new(Maths.Lerp(a.x, b.x, t.x), Maths.Lerp(a.y, b.y, t.y));
        }

        public static double2 InvLerp(double2 edge0, double2 edge1, double2 value)
        {
            return new(Maths.InvLerp(edge0.x, edge1.x, value.x), Maths.InvLerp(edge0.y, edge1.y, value.y));
        }

        public static double2 InvLerp(double2 edge0, double2 edge1, double value)
        {
            return new(Maths.InvLerp(edge0.x, edge1.x, value), Maths.InvLerp(edge0.y, edge1.y, value));
        }

        public static double2 SmoothStep(double2 edge0, double2 edge1, double2 value)
        {
            return new(Maths.SmoothStep(edge0.x, edge1.x, value.x), Maths.SmoothStep(edge0.y, edge1.y, value.y));
        }

        public static double2 SmoothStep(double edge0, double edge1, double2 value)
        {
            return new(Maths.SmoothStep(edge0, edge1, value.x), Maths.SmoothStep(edge0, edge1, value.y));
        }

        public static double2 Step(double2 edge, double2 value)
        {
            return new(Maths.Step(edge.x, value.x), Maths.Step(edge.y, value.y));
        }

        public static double2 Step(double edge, double2 value)
        {
            return new(Maths.Step(edge, value.x), Maths.Step(edge, value.y));
        }

        public static double2 Saturate(double2 value)
        {
            return new(Maths.Saturate(value.x), Maths.Saturate(value.y));
        }

        public static double2 Fma(double2 a, double2 b, double2 c)
        {
            return new(Maths.Fma(a.x, b.x, c.x), Maths.Fma(a.y, b.y, c.y));
        }

        public static double2 Remap(double2 value, double2 sourceFrom, double2 sourceTo, double2 targetFrom, double2 targetTo)
        {
            return new(Maths.Remap(value.x, sourceFrom.x, sourceTo.x, targetFrom.x, targetTo.x), Maths.Remap(value.y, sourceFrom.y, sourceTo.y, targetFrom.y, targetTo.y));
        }

        public static double2 Floor(double2 value)
        {
            return new(Maths.Floor(value.x), Maths.Floor(value.y));
        }

        public static double2 Ceil(double2 value)
        {
            return new(Maths.Ceil(value.x), Maths.Ceil(value.y));
        }

        public static double2 Round(double2 value)
        {
            return new(Maths.Round(value.x), Maths.Round(value.y));
        }

        public static double2 Truncate(double2 value)
        {
            return new(Maths.Truncate(value.x), Maths.Truncate(value.y));
        }

        public static double2 Fract(double2 value)
        {
            return new(Maths.Fract(value.x), Maths.Fract(value.y));
        }

        public static double2 Radians(double2 value)
        {
            return new(Maths.Radians(value.x), Maths.Radians(value.y));
        }

        public static double2 Degrees(double2 value)
        {
            return new(Maths.Degrees(value.x), Maths.Degrees(value.y));
        }
    }
}
