// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace DVG.Maths
{
    public partial struct double2
    {

        public static double2 Exp(double2 value)
        {
            return new(Maths.Exp(value.x), Maths.Exp(value.y));
        }

        public static double2 Exp2(double2 value)
        {
            return new(Maths.Exp2(value.x), Maths.Exp2(value.y));
        }

        public static double2 Log(double2 value)
        {
            return new(Maths.Log(value.x), Maths.Log(value.y));
        }

        public static double2 Log2(double2 value)
        {
            return new(Maths.Log2(value.x), Maths.Log2(value.y));
        }

        public static double2 Log10(double2 value)
        {
            return new(Maths.Log10(value.x), Maths.Log10(value.y));
        }

        public static double2 Sqrt(double2 value)
        {
            return new(Maths.Sqrt(value.x), Maths.Sqrt(value.y));
        }

        public static double2 InverseSqrt(double2 value)
        {
            return new(Maths.InverseSqrt(value.x), Maths.InverseSqrt(value.y));
        }

        public static double2 Cbrt(double2 value)
        {
            return new(Maths.Cbrt(value.x), Maths.Cbrt(value.y));
        }

        public static double2 Pow(double2 a, double2 b)
        {
            return new(Maths.Pow(a.x, b.x), Maths.Pow(a.y, b.y));
        }

        public static double2 Pow(double2 a, double b)
        {
            return new(Maths.Pow(a.x, b), Maths.Pow(a.y, b));
        }

        public static double2 Pow(double a, double2 b)
        {
            return new(Maths.Pow(a, b.x), Maths.Pow(a, b.y));
        }
    }
}
