// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace DVG.Maths
{
    public partial struct double4
    {

        public static double Dot(double4 a, double4 b)
        {
            return a.x * b.x + a.y * b.y + a.z * b.z + a.w * b.w;
        }

        public static double SqrLength(double4 value)
        {
            return value.x * value.x + value.y * value.y + value.z * value.z + value.w * value.w;
        }

        public static double Length(double4 value)
        {
            return Maths.Sqrt(SqrLength(value));
        }

        public static double Distance(double4 a, double4 b)
        {
            return Length(a - b);
        }

        public static double SqrDistance(double4 a, double4 b)
        {
            return SqrLength(a - b);
        }

        public static double4 Normalize(double4 value)
        {
            return value / Length(value);
        }

        public static double4 NormalizeSafe(double4 value)
        {
            var sqrLength = SqrLength(value);
            return sqrLength <= 2.2250738585072014E-308 ? zero : value * Maths.InverseSqrt(sqrLength);
        }

        public static double4 NormalizeSafe(double4 value, double4 fallback)
        {
            var sqrLength = SqrLength(value);
            return sqrLength <= 2.2250738585072014E-308 ? fallback : value * Maths.InverseSqrt(sqrLength);
        }

        public static double4 FaceForward(double4 N, double4 I, double4 Nref)
        {
            return Dot(Nref, I) < 0 ? N : -N;
        }

        public static double4 Reflect(double4 I, double4 N)
        {
            return I - 2 * Dot(N, I) * N;
        }

        public static double4 Refract(double4 I, double4 N, double eta)
        {
            var dNI = Dot(N, I);
            var k = 1 - eta * eta * (1 - dNI * dNI);
            if (k < 0) return zero;
            return eta * I - (eta * dNI + Maths.Sqrt(k)) * N;
        }

        public static double4 Project(double4 value, double4 onto)
        {
            return onto * (Dot(value, onto) / SqrLength(onto));
        }

        public static double4 ProjectSafe(double4 value, double4 onto)
        {
            var denominator = SqrLength(onto);
            return denominator == 0 ? zero : onto * (Dot(value, onto) / denominator);
        }

        public static double4 ClampLength(double4 value, double maxLength)
        {
            maxLength = Maths.Max(maxLength, 0);
            var sqrLength = SqrLength(value);
            if (sqrLength > maxLength * maxLength)
            {
                return value * maxLength * Maths.InverseSqrt(sqrLength);
            }
            return value;
        }

        public static double4 MoveTowards(double4 current, double4 target, double maxDelta)
        {
            maxDelta = Maths.Max(maxDelta, 0);
            var delta = target - current;
            var sqrDistance = SqrLength(delta);
            if (sqrDistance == 0 || sqrDistance <= maxDelta * maxDelta)
                return target;
            return current + delta * maxDelta * Maths.InverseSqrt(sqrDistance);
        }

        public static double4 SmoothDamp(double4 source, double4 target, ref double4 velocity, double smoothTime, double deltaTime)
        {
            return new(Maths.SmoothDamp(source.x, target.x, ref velocity.x, smoothTime, deltaTime), Maths.SmoothDamp(source.y, target.y, ref velocity.y, smoothTime, deltaTime), Maths.SmoothDamp(source.z, target.z, ref velocity.z, smoothTime, deltaTime), Maths.SmoothDamp(source.w, target.w, ref velocity.w, smoothTime, deltaTime));
        }
    }
}
