// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace DVG.Maths
{
    public partial struct double2
    {

        public static double2 Select(double2 falseValue, double2 trueValue, bool2 mask)
        {
            return new(mask.x ? trueValue.x : falseValue.x, mask.y ? trueValue.y : falseValue.y);
        }

        public static double2 Select(double2 falseValue, double2 trueValue, bool mask)
        {
            return new(mask ? trueValue.x : falseValue.x, mask ? trueValue.y : falseValue.y);
        }

        public static double2 Select(double falseValue, double trueValue, bool2 mask)
        {
            return new(mask.x ? trueValue : falseValue, mask.y ? trueValue : falseValue);
        }

        public static bool2 Equal(double2 a, double2 b)
        {
            return new(a.x == b.x, a.y == b.y);
        }

        public static bool2 Equal(double2 a, double b)
        {
            return new(a.x == b, a.y == b);
        }

        public static bool2 Equal(double a, double2 b)
        {
            return new(a == b.x, a == b.y);
        }

        public static bool2 NotEqual(double2 a, double2 b)
        {
            return new(a.x != b.x, a.y != b.y);
        }

        public static bool2 NotEqual(double2 a, double b)
        {
            return new(a.x != b, a.y != b);
        }

        public static bool2 NotEqual(double a, double2 b)
        {
            return new(a != b.x, a != b.y);
        }

        public static bool2 LessThan(double2 a, double2 b)
        {
            return new(a.x < b.x, a.y < b.y);
        }

        public static bool2 LessThan(double2 a, double b)
        {
            return new(a.x < b, a.y < b);
        }

        public static bool2 LessThan(double a, double2 b)
        {
            return new(a < b.x, a < b.y);
        }

        public static bool2 LessThanOrEqual(double2 a, double2 b)
        {
            return new(a.x <= b.x, a.y <= b.y);
        }

        public static bool2 LessThanOrEqual(double2 a, double b)
        {
            return new(a.x <= b, a.y <= b);
        }

        public static bool2 LessThanOrEqual(double a, double2 b)
        {
            return new(a <= b.x, a <= b.y);
        }

        public static bool2 GreaterThan(double2 a, double2 b)
        {
            return new(a.x > b.x, a.y > b.y);
        }

        public static bool2 GreaterThan(double2 a, double b)
        {
            return new(a.x > b, a.y > b);
        }

        public static bool2 GreaterThan(double a, double2 b)
        {
            return new(a > b.x, a > b.y);
        }

        public static bool2 GreaterThanOrEqual(double2 a, double2 b)
        {
            return new(a.x >= b.x, a.y >= b.y);
        }

        public static bool2 GreaterThanOrEqual(double2 a, double b)
        {
            return new(a.x >= b, a.y >= b);
        }

        public static bool2 GreaterThanOrEqual(double a, double2 b)
        {
            return new(a >= b.x, a >= b.y);
        }

        public static bool2 IsNaN(double2 value)
        {
            return new(Maths.IsNaN(value.x), Maths.IsNaN(value.y));
        }

        public static bool2 IsInfinity(double2 value)
        {
            return new(Maths.IsInfinity(value.x), Maths.IsInfinity(value.y));
        }

        public static bool2 IsFinite(double2 value)
        {
            return new(Maths.IsFinite(value.x), Maths.IsFinite(value.y));
        }
    }
}
