// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace DVG.Maths
{
    public partial struct double2
    {

        public static double2 Sin(double2 value)
        {
            return new(Maths.Sin(value.x), Maths.Sin(value.y));
        }

        public static double2 Cos(double2 value)
        {
            return new(Maths.Cos(value.x), Maths.Cos(value.y));
        }

        public static double2 Tan(double2 value)
        {
            return new(Maths.Tan(value.x), Maths.Tan(value.y));
        }

        public static double2 Asin(double2 value)
        {
            return new(Maths.Asin(value.x), Maths.Asin(value.y));
        }

        public static double2 Acos(double2 value)
        {
            return new(Maths.Acos(value.x), Maths.Acos(value.y));
        }

        public static double2 Atan(double2 value)
        {
            return new(Maths.Atan(value.x), Maths.Atan(value.y));
        }

        public static double2 Atan2(double2 y, double2 x)
        {
            return new(Maths.Atan2(y.x, x.x), Maths.Atan2(y.y, x.y));
        }

        public static double2 Atan2(double2 y, double x)
        {
            return new(Maths.Atan2(y.x, x), Maths.Atan2(y.y, x));
        }

        public static double2 Atan2(double y, double2 x)
        {
            return new(Maths.Atan2(y, x.x), Maths.Atan2(y, x.y));
        }

        public static double2 Sinh(double2 value)
        {
            return new(Maths.Sinh(value.x), Maths.Sinh(value.y));
        }

        public static double2 Cosh(double2 value)
        {
            return new(Maths.Cosh(value.x), Maths.Cosh(value.y));
        }

        public static double2 Tanh(double2 value)
        {
            return new(Maths.Tanh(value.x), Maths.Tanh(value.y));
        }

        public static double2 Asinh(double2 value)
        {
            return new(Maths.Asinh(value.x), Maths.Asinh(value.y));
        }

        public static double2 Acosh(double2 value)
        {
            return new(Maths.Acosh(value.x), Maths.Acosh(value.y));
        }

        public static double2 Atanh(double2 value)
        {
            return new(Maths.Atanh(value.x), Maths.Atanh(value.y));
        }
    }
}
