// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace DVG.Maths
{
    public partial struct double4
    {

        public static bool operator ==(double4 left, double4 right)
        {
            return left.x == right.x && left.y == right.y && left.z == right.z && left.w == right.w;
        }

        public static bool operator !=(double4 left, double4 right)
        {
            return left.x != right.x || left.y != right.y || left.z != right.z || left.w != right.w;
        }

        public static double4 operator +(double4 value)
        {
            return new(+value.x, +value.y, +value.z, +value.w);
        }

        public static double4 operator -(double4 value)
        {
            return new(-value.x, -value.y, -value.z, -value.w);
        }

        public static double4 operator ++(double4 value)
        {
            return new(++value.x, ++value.y, ++value.z, ++value.w);
        }

        public static double4 operator --(double4 value)
        {
            return new(--value.x, --value.y, --value.z, --value.w);
        }

        public static double4 operator +(double4 left, double4 right)
        {
            return new(left.x + right.x, left.y + right.y, left.z + right.z, left.w + right.w);
        }

        public static double4 operator -(double4 left, double4 right)
        {
            return new(left.x - right.x, left.y - right.y, left.z - right.z, left.w - right.w);
        }

        public static double4 operator *(double4 left, double4 right)
        {
            return new(left.x * right.x, left.y * right.y, left.z * right.z, left.w * right.w);
        }

        public static double4 operator /(double4 left, double4 right)
        {
            return new(left.x / right.x, left.y / right.y, left.z / right.z, left.w / right.w);
        }

        public static double4 operator +(double4 left, double right)
        {
            return new(left.x + right, left.y + right, left.z + right, left.w + right);
        }

        public static double4 operator +(double left, double4 right)
        {
            return new(left + right.x, left + right.y, left + right.z, left + right.w);
        }

        public static double4 operator -(double4 left, double right)
        {
            return new(left.x - right, left.y - right, left.z - right, left.w - right);
        }

        public static double4 operator -(double left, double4 right)
        {
            return new(left - right.x, left - right.y, left - right.z, left - right.w);
        }

        public static double4 operator *(double4 left, double right)
        {
            return new(left.x * right, left.y * right, left.z * right, left.w * right);
        }

        public static double4 operator *(double left, double4 right)
        {
            return new(left * right.x, left * right.y, left * right.z, left * right.w);
        }

        public static double4 operator /(double4 left, double right)
        {
            return new(left.x / right, left.y / right, left.z / right, left.w / right);
        }

        public static double4 operator /(double left, double4 right)
        {
            return new(left / right.x, left / right.y, left / right.z, left / right.w);
        }

        public static double4 operator %(double4 left, double4 right)
        {
            return new(left.x % right.x, left.y % right.y, left.z % right.z, left.w % right.w);
        }

        public static double4 operator %(double4 left, double right)
        {
            return new(left.x % right, left.y % right, left.z % right, left.w % right);
        }

        public static double4 operator %(double left, double4 right)
        {
            return new(left % right.x, left % right.y, left % right.z, left % right.w);
        }

        public static bool4 operator <(double4 left, double4 right)
        {
            return new(left.x < right.x, left.y < right.y, left.z < right.z, left.w < right.w);
        }

        public static bool4 operator <(double4 left, double right)
        {
            return new(left.x < right, left.y < right, left.z < right, left.w < right);
        }

        public static bool4 operator <(double left, double4 right)
        {
            return new(left < right.x, left < right.y, left < right.z, left < right.w);
        }

        public static bool4 operator <=(double4 left, double4 right)
        {
            return new(left.x <= right.x, left.y <= right.y, left.z <= right.z, left.w <= right.w);
        }

        public static bool4 operator <=(double4 left, double right)
        {
            return new(left.x <= right, left.y <= right, left.z <= right, left.w <= right);
        }

        public static bool4 operator <=(double left, double4 right)
        {
            return new(left <= right.x, left <= right.y, left <= right.z, left <= right.w);
        }

        public static bool4 operator >(double4 left, double4 right)
        {
            return new(left.x > right.x, left.y > right.y, left.z > right.z, left.w > right.w);
        }

        public static bool4 operator >(double4 left, double right)
        {
            return new(left.x > right, left.y > right, left.z > right, left.w > right);
        }

        public static bool4 operator >(double left, double4 right)
        {
            return new(left > right.x, left > right.y, left > right.z, left > right.w);
        }

        public static bool4 operator >=(double4 left, double4 right)
        {
            return new(left.x >= right.x, left.y >= right.y, left.z >= right.z, left.w >= right.w);
        }

        public static bool4 operator >=(double4 left, double right)
        {
            return new(left.x >= right, left.y >= right, left.z >= right, left.w >= right);
        }

        public static bool4 operator >=(double left, double4 right)
        {
            return new(left >= right.x, left >= right.y, left >= right.z, left >= right.w);
        }

        public static explicit operator int4(double4 value)
        {
            return new int4((int)value.x, (int)value.y, (int)value.z, (int)value.w);
        }

        public static explicit operator uint4(double4 value)
        {
            return new uint4((uint)value.x, (uint)value.y, (uint)value.z, (uint)value.w);
        }

        public static explicit operator float4(double4 value)
        {
            return new float4((float)value.x, (float)value.y, (float)value.z, (float)value.w);
        }

        public static explicit operator fix4(double4 value)
        {
            return new fix4((fix)value.x, (fix)value.y, (fix)value.z, (fix)value.w);
        }
    }
}
