// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct double2
    {

        public static bool operator ==(double2 left, double2 right)
        {
            return left.x == right.x && left.y == right.y;
        }

        public static bool operator !=(double2 left, double2 right)
        {
            return left.x != right.x || left.y != right.y;
        }

        public static double2 operator +(double2 value)
        {
            return new(+value.x, +value.y);
        }

        public static double2 operator -(double2 value)
        {
            return new(-value.x, -value.y);
        }

        public static double2 operator ++(double2 value)
        {
            return new(++value.x, ++value.y);
        }

        public static double2 operator --(double2 value)
        {
            return new(--value.x, --value.y);
        }

        public static double2 operator +(double2 left, double2 right)
        {
            return new(left.x + right.x, left.y + right.y);
        }

        public static double2 operator -(double2 left, double2 right)
        {
            return new(left.x - right.x, left.y - right.y);
        }

        public static double2 operator *(double2 left, double2 right)
        {
            return new(left.x * right.x, left.y * right.y);
        }

        public static double2 operator /(double2 left, double2 right)
        {
            return new(left.x / right.x, left.y / right.y);
        }

        public static double2 operator +(double2 left, double right)
        {
            return new(left.x + right, left.y + right);
        }

        public static double2 operator +(double left, double2 right)
        {
            return new(left + right.x, left + right.y);
        }

        public static double2 operator -(double2 left, double right)
        {
            return new(left.x - right, left.y - right);
        }

        public static double2 operator -(double left, double2 right)
        {
            return new(left - right.x, left - right.y);
        }

        public static double2 operator *(double2 left, double right)
        {
            return new(left.x * right, left.y * right);
        }

        public static double2 operator *(double left, double2 right)
        {
            return new(left * right.x, left * right.y);
        }

        public static double2 operator /(double2 left, double right)
        {
            return new(left.x / right, left.y / right);
        }

        public static double2 operator /(double left, double2 right)
        {
            return new(left / right.x, left / right.y);
        }

        public static double2 operator %(double2 left, double2 right)
        {
            return new(left.x % right.x, left.y % right.y);
        }

        public static double2 operator %(double2 left, double right)
        {
            return new(left.x % right, left.y % right);
        }

        public static double2 operator %(double left, double2 right)
        {
            return new(left % right.x, left % right.y);
        }

        public static bool2 operator <(double2 left, double2 right)
        {
            return new(left.x < right.x, left.y < right.y);
        }

        public static bool2 operator <(double2 left, double right)
        {
            return new(left.x < right, left.y < right);
        }

        public static bool2 operator <(double left, double2 right)
        {
            return new(left < right.x, left < right.y);
        }

        public static bool2 operator <=(double2 left, double2 right)
        {
            return new(left.x <= right.x, left.y <= right.y);
        }

        public static bool2 operator <=(double2 left, double right)
        {
            return new(left.x <= right, left.y <= right);
        }

        public static bool2 operator <=(double left, double2 right)
        {
            return new(left <= right.x, left <= right.y);
        }

        public static bool2 operator >(double2 left, double2 right)
        {
            return new(left.x > right.x, left.y > right.y);
        }

        public static bool2 operator >(double2 left, double right)
        {
            return new(left.x > right, left.y > right);
        }

        public static bool2 operator >(double left, double2 right)
        {
            return new(left > right.x, left > right.y);
        }

        public static bool2 operator >=(double2 left, double2 right)
        {
            return new(left.x >= right.x, left.y >= right.y);
        }

        public static bool2 operator >=(double2 left, double right)
        {
            return new(left.x >= right, left.y >= right);
        }

        public static bool2 operator >=(double left, double2 right)
        {
            return new(left >= right.x, left >= right.y);
        }

        public static explicit operator int2(double2 value)
        {
            return new int2((int)value.x, (int)value.y);
        }

        public static explicit operator uint2(double2 value)
        {
            return new uint2((uint)value.x, (uint)value.y);
        }

        public static explicit operator float2(double2 value)
        {
            return new float2((float)value.x, (float)value.y);
        }

        public static explicit operator fix2(double2 value)
        {
            return new fix2((fix)value.x, (fix)value.y);
        }
    }
}
