// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct double3
    {

        public static double3 Min(double3 a, double3 b)
        {
            return new(Maths.Min(a.x, b.x), Maths.Min(a.y, b.y), Maths.Min(a.z, b.z));
        }

        public static double3 Min(double3 a, double b)
        {
            return new(Maths.Min(a.x, b), Maths.Min(a.y, b), Maths.Min(a.z, b));
        }

        public static double3 Min(double a, double3 b)
        {
            return new(Maths.Min(a, b.x), Maths.Min(a, b.y), Maths.Min(a, b.z));
        }

        public static double3 Max(double3 a, double3 b)
        {
            return new(Maths.Max(a.x, b.x), Maths.Max(a.y, b.y), Maths.Max(a.z, b.z));
        }

        public static double3 Max(double3 a, double b)
        {
            return new(Maths.Max(a.x, b), Maths.Max(a.y, b), Maths.Max(a.z, b));
        }

        public static double3 Max(double a, double3 b)
        {
            return new(Maths.Max(a, b.x), Maths.Max(a, b.y), Maths.Max(a, b.z));
        }

        public static double3 Clamp(double3 value, double min, double max)
        {
            return new(Maths.Clamp(value.x, min, max), Maths.Clamp(value.y, min, max), Maths.Clamp(value.z, min, max));
        }

        public static double3 Clamp(double3 value, double3 min, double3 max)
        {
            return new(Maths.Clamp(value.x, min.x, max.x), Maths.Clamp(value.y, min.y, max.y), Maths.Clamp(value.z, min.z, max.z));
        }

        public static double3 Abs(double3 value)
        {
            return new(Maths.Abs(value.x), Maths.Abs(value.y), Maths.Abs(value.z));
        }

        public static double3 Sign(double3 value)
        {
            return new(Maths.Sign(value.x), Maths.Sign(value.y), Maths.Sign(value.z));
        }

        public static double Sum(double3 value)
        {
            return value.x + value.y + value.z;
        }

        public static double3 Lerp(double3 a, double3 b, double t)
        {
            return new(Maths.Lerp(a.x, b.x, t), Maths.Lerp(a.y, b.y, t), Maths.Lerp(a.z, b.z, t));
        }

        public static double3 Lerp(double3 a, double3 b, double3 t)
        {
            return new(Maths.Lerp(a.x, b.x, t.x), Maths.Lerp(a.y, b.y, t.y), Maths.Lerp(a.z, b.z, t.z));
        }

        public static double3 InvLerp(double3 edge0, double3 edge1, double3 value)
        {
            return new(Maths.InvLerp(edge0.x, edge1.x, value.x), Maths.InvLerp(edge0.y, edge1.y, value.y), Maths.InvLerp(edge0.z, edge1.z, value.z));
        }

        public static double3 InvLerp(double3 edge0, double3 edge1, double value)
        {
            return new(Maths.InvLerp(edge0.x, edge1.x, value), Maths.InvLerp(edge0.y, edge1.y, value), Maths.InvLerp(edge0.z, edge1.z, value));
        }

        public static double3 SmoothStep(double3 edge0, double3 edge1, double3 value)
        {
            return new(Maths.SmoothStep(edge0.x, edge1.x, value.x), Maths.SmoothStep(edge0.y, edge1.y, value.y), Maths.SmoothStep(edge0.z, edge1.z, value.z));
        }

        public static double3 SmoothStep(double edge0, double edge1, double3 value)
        {
            return new(Maths.SmoothStep(edge0, edge1, value.x), Maths.SmoothStep(edge0, edge1, value.y), Maths.SmoothStep(edge0, edge1, value.z));
        }

        public static double3 Step(double3 edge, double3 value)
        {
            return new(Maths.Step(edge.x, value.x), Maths.Step(edge.y, value.y), Maths.Step(edge.z, value.z));
        }

        public static double3 Step(double edge, double3 value)
        {
            return new(Maths.Step(edge, value.x), Maths.Step(edge, value.y), Maths.Step(edge, value.z));
        }

        public static double3 Saturate(double3 value)
        {
            return new(Maths.Saturate(value.x), Maths.Saturate(value.y), Maths.Saturate(value.z));
        }

        public static double3 Fma(double3 a, double3 b, double3 c)
        {
            return new(Maths.Fma(a.x, b.x, c.x), Maths.Fma(a.y, b.y, c.y), Maths.Fma(a.z, b.z, c.z));
        }

        public static double3 Remap(double3 value, double3 sourceFrom, double3 sourceTo, double3 targetFrom, double3 targetTo)
        {
            return new(Maths.Remap(value.x, sourceFrom.x, sourceTo.x, targetFrom.x, targetTo.x), Maths.Remap(value.y, sourceFrom.y, sourceTo.y, targetFrom.y, targetTo.y), Maths.Remap(value.z, sourceFrom.z, sourceTo.z, targetFrom.z, targetTo.z));
        }

        public static double3 Floor(double3 value)
        {
            return new(Maths.Floor(value.x), Maths.Floor(value.y), Maths.Floor(value.z));
        }

        public static double3 Ceil(double3 value)
        {
            return new(Maths.Ceil(value.x), Maths.Ceil(value.y), Maths.Ceil(value.z));
        }

        public static double3 Round(double3 value)
        {
            return new(Maths.Round(value.x), Maths.Round(value.y), Maths.Round(value.z));
        }

        public static double3 Truncate(double3 value)
        {
            return new(Maths.Truncate(value.x), Maths.Truncate(value.y), Maths.Truncate(value.z));
        }

        public static double3 Fract(double3 value)
        {
            return new(Maths.Fract(value.x), Maths.Fract(value.y), Maths.Fract(value.z));
        }

        public static double3 Radians(double3 value)
        {
            return new(Maths.Radians(value.x), Maths.Radians(value.y), Maths.Radians(value.z));
        }

        public static double3 Degrees(double3 value)
        {
            return new(Maths.Degrees(value.x), Maths.Degrees(value.y), Maths.Degrees(value.z));
        }
    }
}
