// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct double3
    {

        public static double3 Sin(double3 value)
        {
            return new(Maths.Sin(value.x), Maths.Sin(value.y), Maths.Sin(value.z));
        }

        public static double3 Cos(double3 value)
        {
            return new(Maths.Cos(value.x), Maths.Cos(value.y), Maths.Cos(value.z));
        }

        public static double3 Tan(double3 value)
        {
            return new(Maths.Tan(value.x), Maths.Tan(value.y), Maths.Tan(value.z));
        }

        public static double3 Asin(double3 value)
        {
            return new(Maths.Asin(value.x), Maths.Asin(value.y), Maths.Asin(value.z));
        }

        public static double3 Acos(double3 value)
        {
            return new(Maths.Acos(value.x), Maths.Acos(value.y), Maths.Acos(value.z));
        }

        public static double3 Atan(double3 value)
        {
            return new(Maths.Atan(value.x), Maths.Atan(value.y), Maths.Atan(value.z));
        }

        public static double3 Atan2(double3 y, double3 x)
        {
            return new(Maths.Atan2(y.x, x.x), Maths.Atan2(y.y, x.y), Maths.Atan2(y.z, x.z));
        }

        public static double3 Atan2(double3 y, double x)
        {
            return new(Maths.Atan2(y.x, x), Maths.Atan2(y.y, x), Maths.Atan2(y.z, x));
        }

        public static double3 Atan2(double y, double3 x)
        {
            return new(Maths.Atan2(y, x.x), Maths.Atan2(y, x.y), Maths.Atan2(y, x.z));
        }

        public static double3 Sinh(double3 value)
        {
            return new(Maths.Sinh(value.x), Maths.Sinh(value.y), Maths.Sinh(value.z));
        }

        public static double3 Cosh(double3 value)
        {
            return new(Maths.Cosh(value.x), Maths.Cosh(value.y), Maths.Cosh(value.z));
        }

        public static double3 Tanh(double3 value)
        {
            return new(Maths.Tanh(value.x), Maths.Tanh(value.y), Maths.Tanh(value.z));
        }

        public static double3 Asinh(double3 value)
        {
            return new(Maths.Asinh(value.x), Maths.Asinh(value.y), Maths.Asinh(value.z));
        }

        public static double3 Acosh(double3 value)
        {
            return new(Maths.Acosh(value.x), Maths.Acosh(value.y), Maths.Acosh(value.z));
        }

        public static double3 Atanh(double3 value)
        {
            return new(Maths.Atanh(value.x), Maths.Atanh(value.y), Maths.Atanh(value.z));
        }
    }
}
