// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct double3
    {

        public static double3 Exp(double3 value)
        {
            return new(Maths.Exp(value.x), Maths.Exp(value.y), Maths.Exp(value.z));
        }

        public static double3 Exp2(double3 value)
        {
            return new(Maths.Exp2(value.x), Maths.Exp2(value.y), Maths.Exp2(value.z));
        }

        public static double3 Log(double3 value)
        {
            return new(Maths.Log(value.x), Maths.Log(value.y), Maths.Log(value.z));
        }

        public static double3 Log2(double3 value)
        {
            return new(Maths.Log2(value.x), Maths.Log2(value.y), Maths.Log2(value.z));
        }

        public static double3 Log10(double3 value)
        {
            return new(Maths.Log10(value.x), Maths.Log10(value.y), Maths.Log10(value.z));
        }

        public static double3 Sqrt(double3 value)
        {
            return new(Maths.Sqrt(value.x), Maths.Sqrt(value.y), Maths.Sqrt(value.z));
        }

        public static double3 InverseSqrt(double3 value)
        {
            return new(Maths.InverseSqrt(value.x), Maths.InverseSqrt(value.y), Maths.InverseSqrt(value.z));
        }

        public static double3 Cbrt(double3 value)
        {
            return new(Maths.Cbrt(value.x), Maths.Cbrt(value.y), Maths.Cbrt(value.z));
        }

        public static double3 Pow(double3 a, double3 b)
        {
            return new(Maths.Pow(a.x, b.x), Maths.Pow(a.y, b.y), Maths.Pow(a.z, b.z));
        }

        public static double3 Pow(double3 a, double b)
        {
            return new(Maths.Pow(a.x, b), Maths.Pow(a.y, b), Maths.Pow(a.z, b));
        }

        public static double3 Pow(double a, double3 b)
        {
            return new(Maths.Pow(a, b.x), Maths.Pow(a, b.y), Maths.Pow(a, b.z));
        }
    }
}
