// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    /// <summary>A vector of type double with 3 components.</summary>
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    [System.Runtime.Serialization.DataContract]
    public partial struct double3 : IEquatable<double3>, IComparable<double3>
    {

        [System.Runtime.Serialization.DataMember(Order = 0)]
        public double x;

        [System.Runtime.Serialization.DataMember(Order = 1)]
        public double y;

        [System.Runtime.Serialization.DataMember(Order = 2)]
        public double z;

        public static readonly double3 zero = new double3(0.0, 0.0, 0.0);

        public double3(double x, double y, double z)
        {
            this.x = x;
            this.y = y;
            this.z = z;
        }

        public double3(double value)
        {
            x = value;
            y = value;
            z = value;
        }

        public double3(double2 value)
        {
            x = value.x;
            y = value.y;
            z = 0.0;
        }

        public double3(double3 value)
        {
            x = value.x;
            y = value.y;
            z = value.z;
        }

        public double3(double4 value)
        {
            x = value.x;
            y = value.y;
            z = value.z;
        }

        public double3(double x, double2 yz)
        {
            this.x = x;
            this.y = yz.x;
            this.z = yz.y;
        }

        public double3(double2 xy, double z)
        {
            this.x = xy.x;
            this.y = xy.y;
            this.z = z;
        }

        public double this[int index]
        {
            get
            {
                if ((uint)index >= Count)
                    throw new ArgumentOutOfRangeException(nameof(index));
                return Unsafe.Add(ref x, index);
            }
            set
            {
                if ((uint)index >= Count)
                    throw new ArgumentOutOfRangeException(nameof(index));
                Unsafe.Add(ref x, index) = value;
            }
        }

        public int Count => 3;

        public bool Equals(double3 other)
        {
            return x.Equals(other.x) && y.Equals(other.y) && z.Equals(other.z);
        }

        public override bool Equals(object obj)
        {
            return obj is double3 other && Equals(other);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                var hash = 17;
                hash = hash * 31 + x.GetHashCode();
                hash = hash * 31 + y.GetHashCode();
                hash = hash * 31 + z.GetHashCode();
                return hash;
            }
        }

        public int CompareTo(double3 other)
        {
            var xComparison = x.CompareTo(other.x);
            if (xComparison != 0) return xComparison;
            var yComparison = y.CompareTo(other.y);
            if (yComparison != 0) return yComparison;
            var zComparison = z.CompareTo(other.z);
            if (zComparison != 0) return zComparison;
            return 0;
        }

        public override string ToString()
        {
            return FormattableString.Invariant($"{x}, {y}, {z}");
        }

        public static double3 Parse(string value)
        {
            value = value.Trim();
            if (value.Length >= 2 && value[0] == '[' && value[value.Length - 1] == ']')
                value = value.Substring(1, value.Length - 2);
            var values = value.Split(',');
            if (values.Length != 3)
                throw new FormatException("Expected 3 vector components.");
            return new(double.Parse(values[0].Trim(), System.Globalization.CultureInfo.InvariantCulture), double.Parse(values[1].Trim(), System.Globalization.CultureInfo.InvariantCulture), double.Parse(values[2].Trim(), System.Globalization.CultureInfo.InvariantCulture));
        }

        public static double3 Parse(string value, IFormatProvider format)
        {
            value = value.Trim();
            if (value.Length >= 2 && value[0] == '[' && value[value.Length - 1] == ']')
                value = value.Substring(1, value.Length - 2);
            var values = value.Split(',');
            if (values.Length != 3)
                throw new FormatException("Expected 3 vector components.");
            return new(double.Parse(values[0].Trim(), format), double.Parse(values[1].Trim(), format), double.Parse(values[2].Trim(), format));
        }
    }
}
