// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace DVG.Maths
{
    public partial struct double4
    {

        public static double4 Exp(double4 value)
        {
            return new(Maths.Exp(value.x), Maths.Exp(value.y), Maths.Exp(value.z), Maths.Exp(value.w));
        }

        public static double4 Exp2(double4 value)
        {
            return new(Maths.Exp2(value.x), Maths.Exp2(value.y), Maths.Exp2(value.z), Maths.Exp2(value.w));
        }

        public static double4 Log(double4 value)
        {
            return new(Maths.Log(value.x), Maths.Log(value.y), Maths.Log(value.z), Maths.Log(value.w));
        }

        public static double4 Log2(double4 value)
        {
            return new(Maths.Log2(value.x), Maths.Log2(value.y), Maths.Log2(value.z), Maths.Log2(value.w));
        }

        public static double4 Log10(double4 value)
        {
            return new(Maths.Log10(value.x), Maths.Log10(value.y), Maths.Log10(value.z), Maths.Log10(value.w));
        }

        public static double4 Sqrt(double4 value)
        {
            return new(Maths.Sqrt(value.x), Maths.Sqrt(value.y), Maths.Sqrt(value.z), Maths.Sqrt(value.w));
        }

        public static double4 InverseSqrt(double4 value)
        {
            return new(Maths.InverseSqrt(value.x), Maths.InverseSqrt(value.y), Maths.InverseSqrt(value.z), Maths.InverseSqrt(value.w));
        }

        public static double4 Cbrt(double4 value)
        {
            return new(Maths.Cbrt(value.x), Maths.Cbrt(value.y), Maths.Cbrt(value.z), Maths.Cbrt(value.w));
        }

        public static double4 Pow(double4 a, double4 b)
        {
            return new(Maths.Pow(a.x, b.x), Maths.Pow(a.y, b.y), Maths.Pow(a.z, b.z), Maths.Pow(a.w, b.w));
        }

        public static double4 Pow(double4 a, double b)
        {
            return new(Maths.Pow(a.x, b), Maths.Pow(a.y, b), Maths.Pow(a.z, b), Maths.Pow(a.w, b));
        }

        public static double4 Pow(double a, double4 b)
        {
            return new(Maths.Pow(a, b.x), Maths.Pow(a, b.y), Maths.Pow(a, b.z), Maths.Pow(a, b.w));
        }
    }
}
