// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace KibiHex
{
    public partial struct fix2
    {

        public static fix2 Select(fix2 falseValue, fix2 trueValue, bool2 mask)
        {
            return new(mask.x ? trueValue.x : falseValue.x, mask.y ? trueValue.y : falseValue.y);
        }

        public static fix2 Select(fix2 falseValue, fix2 trueValue, bool mask)
        {
            return new(mask ? trueValue.x : falseValue.x, mask ? trueValue.y : falseValue.y);
        }

        public static fix2 Select(fix falseValue, fix trueValue, bool2 mask)
        {
            return new(mask.x ? trueValue : falseValue, mask.y ? trueValue : falseValue);
        }

        public static bool2 Equal(fix2 a, fix2 b)
        {
            return new(a.x == b.x, a.y == b.y);
        }

        public static bool2 Equal(fix2 a, fix b)
        {
            return new(a.x == b, a.y == b);
        }

        public static bool2 Equal(fix a, fix2 b)
        {
            return new(a == b.x, a == b.y);
        }

        public static bool2 NotEqual(fix2 a, fix2 b)
        {
            return new(a.x != b.x, a.y != b.y);
        }

        public static bool2 NotEqual(fix2 a, fix b)
        {
            return new(a.x != b, a.y != b);
        }

        public static bool2 NotEqual(fix a, fix2 b)
        {
            return new(a != b.x, a != b.y);
        }

        public static bool2 LessThan(fix2 a, fix2 b)
        {
            return new(a.x < b.x, a.y < b.y);
        }

        public static bool2 LessThan(fix2 a, fix b)
        {
            return new(a.x < b, a.y < b);
        }

        public static bool2 LessThan(fix a, fix2 b)
        {
            return new(a < b.x, a < b.y);
        }

        public static bool2 LessThanOrEqual(fix2 a, fix2 b)
        {
            return new(a.x <= b.x, a.y <= b.y);
        }

        public static bool2 LessThanOrEqual(fix2 a, fix b)
        {
            return new(a.x <= b, a.y <= b);
        }

        public static bool2 LessThanOrEqual(fix a, fix2 b)
        {
            return new(a <= b.x, a <= b.y);
        }

        public static bool2 GreaterThan(fix2 a, fix2 b)
        {
            return new(a.x > b.x, a.y > b.y);
        }

        public static bool2 GreaterThan(fix2 a, fix b)
        {
            return new(a.x > b, a.y > b);
        }

        public static bool2 GreaterThan(fix a, fix2 b)
        {
            return new(a > b.x, a > b.y);
        }

        public static bool2 GreaterThanOrEqual(fix2 a, fix2 b)
        {
            return new(a.x >= b.x, a.y >= b.y);
        }

        public static bool2 GreaterThanOrEqual(fix2 a, fix b)
        {
            return new(a.x >= b, a.y >= b);
        }

        public static bool2 GreaterThanOrEqual(fix a, fix2 b)
        {
            return new(a >= b.x, a >= b.y);
        }
    }
}
