// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace KibiHex
{
    public partial struct fix2
    {

        public static fix2 Min(fix2 a, fix2 b)
        {
            return new(Maths.Min(a.x, b.x), Maths.Min(a.y, b.y));
        }

        public static fix2 Min(fix2 a, fix b)
        {
            return new(Maths.Min(a.x, b), Maths.Min(a.y, b));
        }

        public static fix2 Min(fix a, fix2 b)
        {
            return new(Maths.Min(a, b.x), Maths.Min(a, b.y));
        }

        public static fix2 Max(fix2 a, fix2 b)
        {
            return new(Maths.Max(a.x, b.x), Maths.Max(a.y, b.y));
        }

        public static fix2 Max(fix2 a, fix b)
        {
            return new(Maths.Max(a.x, b), Maths.Max(a.y, b));
        }

        public static fix2 Max(fix a, fix2 b)
        {
            return new(Maths.Max(a, b.x), Maths.Max(a, b.y));
        }

        public static fix2 Clamp(fix2 value, fix min, fix max)
        {
            return new(Maths.Clamp(value.x, min, max), Maths.Clamp(value.y, min, max));
        }

        public static fix2 Clamp(fix2 value, fix2 min, fix2 max)
        {
            return new(Maths.Clamp(value.x, min.x, max.x), Maths.Clamp(value.y, min.y, max.y));
        }

        public static fix2 Abs(fix2 value)
        {
            return new(Maths.Abs(value.x), Maths.Abs(value.y));
        }

        public static fix2 Sign(fix2 value)
        {
            return new(Maths.Sign(value.x), Maths.Sign(value.y));
        }

        public static fix Sum(fix2 value)
        {
            return value.x + value.y;
        }

        public static fix2 Lerp(fix2 a, fix2 b, fix t)
        {
            return new(Maths.Lerp(a.x, b.x, t), Maths.Lerp(a.y, b.y, t));
        }

        public static fix2 Lerp(fix2 a, fix2 b, fix2 t)
        {
            return new(Maths.Lerp(a.x, b.x, t.x), Maths.Lerp(a.y, b.y, t.y));
        }

        public static fix2 InvLerp(fix2 edge0, fix2 edge1, fix2 value)
        {
            return new(Maths.InvLerp(edge0.x, edge1.x, value.x), Maths.InvLerp(edge0.y, edge1.y, value.y));
        }

        public static fix2 InvLerp(fix2 edge0, fix2 edge1, fix value)
        {
            return new(Maths.InvLerp(edge0.x, edge1.x, value), Maths.InvLerp(edge0.y, edge1.y, value));
        }

        public static fix2 SmoothStep(fix2 edge0, fix2 edge1, fix2 value)
        {
            return new(Maths.SmoothStep(edge0.x, edge1.x, value.x), Maths.SmoothStep(edge0.y, edge1.y, value.y));
        }

        public static fix2 SmoothStep(fix edge0, fix edge1, fix2 value)
        {
            return new(Maths.SmoothStep(edge0, edge1, value.x), Maths.SmoothStep(edge0, edge1, value.y));
        }

        public static fix2 Step(fix2 edge, fix2 value)
        {
            return new(Maths.Step(edge.x, value.x), Maths.Step(edge.y, value.y));
        }

        public static fix2 Step(fix edge, fix2 value)
        {
            return new(Maths.Step(edge, value.x), Maths.Step(edge, value.y));
        }

        public static fix2 Saturate(fix2 value)
        {
            return new(Maths.Saturate(value.x), Maths.Saturate(value.y));
        }

        public static fix2 Fma(fix2 a, fix2 b, fix2 c)
        {
            return new(Maths.Fma(a.x, b.x, c.x), Maths.Fma(a.y, b.y, c.y));
        }

        public static fix2 Remap(fix2 value, fix2 sourceFrom, fix2 sourceTo, fix2 targetFrom, fix2 targetTo)
        {
            return new(Maths.Remap(value.x, sourceFrom.x, sourceTo.x, targetFrom.x, targetTo.x), Maths.Remap(value.y, sourceFrom.y, sourceTo.y, targetFrom.y, targetTo.y));
        }

        public static fix2 Floor(fix2 value)
        {
            return new(Maths.Floor(value.x), Maths.Floor(value.y));
        }

        public static fix2 Ceil(fix2 value)
        {
            return new(Maths.Ceil(value.x), Maths.Ceil(value.y));
        }

        public static fix2 Round(fix2 value)
        {
            return new(Maths.Round(value.x), Maths.Round(value.y));
        }

        public static fix2 Truncate(fix2 value)
        {
            return new(Maths.Truncate(value.x), Maths.Truncate(value.y));
        }

        public static fix2 Fract(fix2 value)
        {
            return new(Maths.Fract(value.x), Maths.Fract(value.y));
        }

        public static fix2 Radians(fix2 value)
        {
            return new(Maths.Radians(value.x), Maths.Radians(value.y));
        }

        public static fix2 Degrees(fix2 value)
        {
            return new(Maths.Degrees(value.x), Maths.Degrees(value.y));
        }
    }
}
