// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct fix2
    {

        public static fix Dot(fix2 a, fix2 b)
        {
            return a.x * b.x + a.y * b.y;
        }

        public static fix SqrLength(fix2 value)
        {
            return value.x * value.x + value.y * value.y;
        }

        public static fix Length(fix2 value)
        {
            return Maths.Sqrt(SqrLength(value));
        }

        public static fix Distance(fix2 a, fix2 b)
        {
            return Length(a - b);
        }

        public static fix SqrDistance(fix2 a, fix2 b)
        {
            return SqrLength(a - b);
        }

        public static fix2 Normalize(fix2 value)
        {
            return value / Length(value);
        }

        public static fix2 NormalizeSafe(fix2 value)
        {
            var sqrLength = SqrLength(value);
            return sqrLength <= 0 ? zero : value * Maths.InverseSqrt(sqrLength);
        }

        public static fix2 NormalizeSafe(fix2 value, fix2 fallback)
        {
            var sqrLength = SqrLength(value);
            return sqrLength <= 0 ? fallback : value * Maths.InverseSqrt(sqrLength);
        }

        public static fix2 FaceForward(fix2 N, fix2 I, fix2 Nref)
        {
            return Dot(Nref, I) < 0 ? N : -N;
        }

        public static fix2 Reflect(fix2 I, fix2 N)
        {
            return I - 2 * Dot(N, I) * N;
        }

        public static fix2 Refract(fix2 I, fix2 N, fix eta)
        {
            var dNI = Dot(N, I);
            var k = 1 - eta * eta * (1 - dNI * dNI);
            if (k < 0) return zero;
            return eta * I - (eta * dNI + Maths.Sqrt(k)) * N;
        }

        public static fix2 Project(fix2 value, fix2 onto)
        {
            return onto * (Dot(value, onto) / SqrLength(onto));
        }

        public static fix2 ProjectSafe(fix2 value, fix2 onto)
        {
            var denominator = SqrLength(onto);
            return denominator == 0 ? zero : onto * (Dot(value, onto) / denominator);
        }

        public static fix2 ClampLength(fix2 value, fix maxLength)
        {
            maxLength = Maths.Max(maxLength, 0);
            var sqrLength = SqrLength(value);
            if (sqrLength > maxLength * maxLength)
            {
                return value * maxLength * Maths.InverseSqrt(sqrLength);
            }
            return value;
        }

        public static fix2 MoveTowards(fix2 current, fix2 target, fix maxDelta)
        {
            maxDelta = Maths.Max(maxDelta, 0);
            var delta = target - current;
            var sqrDistance = SqrLength(delta);
            if (sqrDistance == 0 || sqrDistance <= maxDelta * maxDelta)
                return target;
            return current + delta * maxDelta * Maths.InverseSqrt(sqrDistance);
        }

        public static fix2 SmoothDamp(fix2 source, fix2 target, ref fix2 velocity, fix smoothTime, fix deltaTime)
        {
            return new(Maths.SmoothDamp(source.x, target.x, ref velocity.x, smoothTime, deltaTime), Maths.SmoothDamp(source.y, target.y, ref velocity.y, smoothTime, deltaTime));
        }
    }
}
