// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace KibiHex
{
    public partial struct fix3
    {

        public static fix3 Sin(fix3 value)
        {
            return new(Maths.Sin(value.x), Maths.Sin(value.y), Maths.Sin(value.z));
        }

        public static fix3 Cos(fix3 value)
        {
            return new(Maths.Cos(value.x), Maths.Cos(value.y), Maths.Cos(value.z));
        }

        public static fix3 Tan(fix3 value)
        {
            return new(Maths.Tan(value.x), Maths.Tan(value.y), Maths.Tan(value.z));
        }

        public static fix3 Asin(fix3 value)
        {
            return new(Maths.Asin(value.x), Maths.Asin(value.y), Maths.Asin(value.z));
        }

        public static fix3 Acos(fix3 value)
        {
            return new(Maths.Acos(value.x), Maths.Acos(value.y), Maths.Acos(value.z));
        }

        public static fix3 Atan(fix3 value)
        {
            return new(Maths.Atan(value.x), Maths.Atan(value.y), Maths.Atan(value.z));
        }

        public static fix3 Atan2(fix3 y, fix3 x)
        {
            return new(Maths.Atan2(y.x, x.x), Maths.Atan2(y.y, x.y), Maths.Atan2(y.z, x.z));
        }

        public static fix3 Atan2(fix3 y, fix x)
        {
            return new(Maths.Atan2(y.x, x), Maths.Atan2(y.y, x), Maths.Atan2(y.z, x));
        }

        public static fix3 Atan2(fix y, fix3 x)
        {
            return new(Maths.Atan2(y, x.x), Maths.Atan2(y, x.y), Maths.Atan2(y, x.z));
        }
    }
}
