// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace KibiHex
{
    public partial struct fix3
    {

        public static fix Dot(fix3 a, fix3 b)
        {
            return a.x * b.x + a.y * b.y + a.z * b.z;
        }

        public static fix SqrLength(fix3 value)
        {
            return value.x * value.x + value.y * value.y + value.z * value.z;
        }

        public static fix Length(fix3 value)
        {
            return Maths.Sqrt(SqrLength(value));
        }

        public static fix Distance(fix3 a, fix3 b)
        {
            return Length(a - b);
        }

        public static fix SqrDistance(fix3 a, fix3 b)
        {
            return SqrLength(a - b);
        }

        public static fix3 Normalize(fix3 value)
        {
            return value / Length(value);
        }

        public static fix3 NormalizeSafe(fix3 value)
        {
            var sqrLength = SqrLength(value);
            return sqrLength <= 0 ? zero : value * Maths.InverseSqrt(sqrLength);
        }

        public static fix3 NormalizeSafe(fix3 value, fix3 fallback)
        {
            var sqrLength = SqrLength(value);
            return sqrLength <= 0 ? fallback : value * Maths.InverseSqrt(sqrLength);
        }

        public static fix3 FaceForward(fix3 N, fix3 I, fix3 Nref)
        {
            return Dot(Nref, I) < 0 ? N : -N;
        }

        public static fix3 Reflect(fix3 I, fix3 N)
        {
            return I - 2 * Dot(N, I) * N;
        }

        public static fix3 Refract(fix3 I, fix3 N, fix eta)
        {
            var dNI = Dot(N, I);
            var k = 1 - eta * eta * (1 - dNI * dNI);
            if (k < 0) return zero;
            return eta * I - (eta * dNI + Maths.Sqrt(k)) * N;
        }

        public static fix3 Project(fix3 value, fix3 onto)
        {
            return onto * (Dot(value, onto) / SqrLength(onto));
        }

        public static fix3 ProjectSafe(fix3 value, fix3 onto)
        {
            var denominator = SqrLength(onto);
            return denominator == 0 ? zero : onto * (Dot(value, onto) / denominator);
        }

        public static fix3 ClampLength(fix3 value, fix maxLength)
        {
            maxLength = Maths.Max(maxLength, 0);
            var sqrLength = SqrLength(value);
            if (sqrLength > maxLength * maxLength)
            {
                return value * maxLength * Maths.InverseSqrt(sqrLength);
            }
            return value;
        }

        public static fix3 MoveTowards(fix3 current, fix3 target, fix maxDelta)
        {
            maxDelta = Maths.Max(maxDelta, 0);
            var delta = target - current;
            var sqrDistance = SqrLength(delta);
            if (sqrDistance == 0 || sqrDistance <= maxDelta * maxDelta)
                return target;
            return current + delta * maxDelta * Maths.InverseSqrt(sqrDistance);
        }

        public static fix3 SmoothDamp(fix3 source, fix3 target, ref fix3 velocity, fix smoothTime, fix deltaTime)
        {
            return new(Maths.SmoothDamp(source.x, target.x, ref velocity.x, smoothTime, deltaTime), Maths.SmoothDamp(source.y, target.y, ref velocity.y, smoothTime, deltaTime), Maths.SmoothDamp(source.z, target.z, ref velocity.z, smoothTime, deltaTime));
        }

        public static fix3 Cross(fix3 a, fix3 b)
        {
            return new(a.y * b.z - a.z * b.y, a.z * b.x - a.x * b.z, a.x * b.y - a.y * b.x);
        }
    }
}
