// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace KibiHex
{
    public partial struct fix3
    {

        public static fix3 Min(fix3 a, fix3 b)
        {
            return new(Maths.Min(a.x, b.x), Maths.Min(a.y, b.y), Maths.Min(a.z, b.z));
        }

        public static fix3 Min(fix3 a, fix b)
        {
            return new(Maths.Min(a.x, b), Maths.Min(a.y, b), Maths.Min(a.z, b));
        }

        public static fix3 Min(fix a, fix3 b)
        {
            return new(Maths.Min(a, b.x), Maths.Min(a, b.y), Maths.Min(a, b.z));
        }

        public static fix3 Max(fix3 a, fix3 b)
        {
            return new(Maths.Max(a.x, b.x), Maths.Max(a.y, b.y), Maths.Max(a.z, b.z));
        }

        public static fix3 Max(fix3 a, fix b)
        {
            return new(Maths.Max(a.x, b), Maths.Max(a.y, b), Maths.Max(a.z, b));
        }

        public static fix3 Max(fix a, fix3 b)
        {
            return new(Maths.Max(a, b.x), Maths.Max(a, b.y), Maths.Max(a, b.z));
        }

        public static fix3 Clamp(fix3 value, fix min, fix max)
        {
            return new(Maths.Clamp(value.x, min, max), Maths.Clamp(value.y, min, max), Maths.Clamp(value.z, min, max));
        }

        public static fix3 Clamp(fix3 value, fix3 min, fix3 max)
        {
            return new(Maths.Clamp(value.x, min.x, max.x), Maths.Clamp(value.y, min.y, max.y), Maths.Clamp(value.z, min.z, max.z));
        }

        public static fix3 Abs(fix3 value)
        {
            return new(Maths.Abs(value.x), Maths.Abs(value.y), Maths.Abs(value.z));
        }

        public static fix3 Sign(fix3 value)
        {
            return new(Maths.Sign(value.x), Maths.Sign(value.y), Maths.Sign(value.z));
        }

        public static fix Sum(fix3 value)
        {
            return value.x + value.y + value.z;
        }

        public static fix3 Lerp(fix3 a, fix3 b, fix t)
        {
            return new(Maths.Lerp(a.x, b.x, t), Maths.Lerp(a.y, b.y, t), Maths.Lerp(a.z, b.z, t));
        }

        public static fix3 Lerp(fix3 a, fix3 b, fix3 t)
        {
            return new(Maths.Lerp(a.x, b.x, t.x), Maths.Lerp(a.y, b.y, t.y), Maths.Lerp(a.z, b.z, t.z));
        }

        public static fix3 InvLerp(fix3 edge0, fix3 edge1, fix3 value)
        {
            return new(Maths.InvLerp(edge0.x, edge1.x, value.x), Maths.InvLerp(edge0.y, edge1.y, value.y), Maths.InvLerp(edge0.z, edge1.z, value.z));
        }

        public static fix3 InvLerp(fix3 edge0, fix3 edge1, fix value)
        {
            return new(Maths.InvLerp(edge0.x, edge1.x, value), Maths.InvLerp(edge0.y, edge1.y, value), Maths.InvLerp(edge0.z, edge1.z, value));
        }

        public static fix3 SmoothStep(fix3 edge0, fix3 edge1, fix3 value)
        {
            return new(Maths.SmoothStep(edge0.x, edge1.x, value.x), Maths.SmoothStep(edge0.y, edge1.y, value.y), Maths.SmoothStep(edge0.z, edge1.z, value.z));
        }

        public static fix3 SmoothStep(fix edge0, fix edge1, fix3 value)
        {
            return new(Maths.SmoothStep(edge0, edge1, value.x), Maths.SmoothStep(edge0, edge1, value.y), Maths.SmoothStep(edge0, edge1, value.z));
        }

        public static fix3 Step(fix3 edge, fix3 value)
        {
            return new(Maths.Step(edge.x, value.x), Maths.Step(edge.y, value.y), Maths.Step(edge.z, value.z));
        }

        public static fix3 Step(fix edge, fix3 value)
        {
            return new(Maths.Step(edge, value.x), Maths.Step(edge, value.y), Maths.Step(edge, value.z));
        }

        public static fix3 Saturate(fix3 value)
        {
            return new(Maths.Saturate(value.x), Maths.Saturate(value.y), Maths.Saturate(value.z));
        }

        public static fix3 Fma(fix3 a, fix3 b, fix3 c)
        {
            return new(Maths.Fma(a.x, b.x, c.x), Maths.Fma(a.y, b.y, c.y), Maths.Fma(a.z, b.z, c.z));
        }

        public static fix3 Remap(fix3 value, fix3 sourceFrom, fix3 sourceTo, fix3 targetFrom, fix3 targetTo)
        {
            return new(Maths.Remap(value.x, sourceFrom.x, sourceTo.x, targetFrom.x, targetTo.x), Maths.Remap(value.y, sourceFrom.y, sourceTo.y, targetFrom.y, targetTo.y), Maths.Remap(value.z, sourceFrom.z, sourceTo.z, targetFrom.z, targetTo.z));
        }

        public static fix3 Floor(fix3 value)
        {
            return new(Maths.Floor(value.x), Maths.Floor(value.y), Maths.Floor(value.z));
        }

        public static fix3 Ceil(fix3 value)
        {
            return new(Maths.Ceil(value.x), Maths.Ceil(value.y), Maths.Ceil(value.z));
        }

        public static fix3 Round(fix3 value)
        {
            return new(Maths.Round(value.x), Maths.Round(value.y), Maths.Round(value.z));
        }

        public static fix3 Truncate(fix3 value)
        {
            return new(Maths.Truncate(value.x), Maths.Truncate(value.y), Maths.Truncate(value.z));
        }

        public static fix3 Fract(fix3 value)
        {
            return new(Maths.Fract(value.x), Maths.Fract(value.y), Maths.Fract(value.z));
        }

        public static fix3 Radians(fix3 value)
        {
            return new(Maths.Radians(value.x), Maths.Radians(value.y), Maths.Radians(value.z));
        }

        public static fix3 Degrees(fix3 value)
        {
            return new(Maths.Degrees(value.x), Maths.Degrees(value.y), Maths.Degrees(value.z));
        }
    }
}
