// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct fix4
    {

        public static fix Dot(fix4 a, fix4 b)
        {
            return a.x * b.x + a.y * b.y + a.z * b.z + a.w * b.w;
        }

        public static fix SqrLength(fix4 value)
        {
            return value.x * value.x + value.y * value.y + value.z * value.z + value.w * value.w;
        }

        public static fix Length(fix4 value)
        {
            return Maths.Sqrt(SqrLength(value));
        }

        public static fix Distance(fix4 a, fix4 b)
        {
            return Length(a - b);
        }

        public static fix SqrDistance(fix4 a, fix4 b)
        {
            return SqrLength(a - b);
        }

        public static fix4 Normalize(fix4 value)
        {
            return value / Length(value);
        }

        public static fix4 NormalizeSafe(fix4 value)
        {
            var sqrLength = SqrLength(value);
            return sqrLength <= 0 ? zero : value * Maths.InverseSqrt(sqrLength);
        }

        public static fix4 NormalizeSafe(fix4 value, fix4 fallback)
        {
            var sqrLength = SqrLength(value);
            return sqrLength <= 0 ? fallback : value * Maths.InverseSqrt(sqrLength);
        }

        public static fix4 FaceForward(fix4 N, fix4 I, fix4 Nref)
        {
            return Dot(Nref, I) < 0 ? N : -N;
        }

        public static fix4 Reflect(fix4 I, fix4 N)
        {
            return I - 2 * Dot(N, I) * N;
        }

        public static fix4 Refract(fix4 I, fix4 N, fix eta)
        {
            var dNI = Dot(N, I);
            var k = 1 - eta * eta * (1 - dNI * dNI);
            if (k < 0) return zero;
            return eta * I - (eta * dNI + Maths.Sqrt(k)) * N;
        }

        public static fix4 Project(fix4 value, fix4 onto)
        {
            return onto * (Dot(value, onto) / SqrLength(onto));
        }

        public static fix4 ProjectSafe(fix4 value, fix4 onto)
        {
            var denominator = SqrLength(onto);
            return denominator == 0 ? zero : onto * (Dot(value, onto) / denominator);
        }

        public static fix4 ClampLength(fix4 value, fix maxLength)
        {
            maxLength = Maths.Max(maxLength, 0);
            var sqrLength = SqrLength(value);
            if (sqrLength > maxLength * maxLength)
            {
                return value * maxLength * Maths.InverseSqrt(sqrLength);
            }
            return value;
        }

        public static fix4 MoveTowards(fix4 current, fix4 target, fix maxDelta)
        {
            maxDelta = Maths.Max(maxDelta, 0);
            var delta = target - current;
            var sqrDistance = SqrLength(delta);
            if (sqrDistance == 0 || sqrDistance <= maxDelta * maxDelta)
                return target;
            return current + delta * maxDelta * Maths.InverseSqrt(sqrDistance);
        }

        public static fix4 SmoothDamp(fix4 source, fix4 target, ref fix4 velocity, fix smoothTime, fix deltaTime)
        {
            return new(Maths.SmoothDamp(source.x, target.x, ref velocity.x, smoothTime, deltaTime), Maths.SmoothDamp(source.y, target.y, ref velocity.y, smoothTime, deltaTime), Maths.SmoothDamp(source.z, target.z, ref velocity.z, smoothTime, deltaTime), Maths.SmoothDamp(source.w, target.w, ref velocity.w, smoothTime, deltaTime));
        }
    }
}
