// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace KibiHex
{
    public partial struct fix4
    {

        public static bool operator ==(fix4 left, fix4 right)
        {
            return left.x == right.x && left.y == right.y && left.z == right.z && left.w == right.w;
        }

        public static bool operator !=(fix4 left, fix4 right)
        {
            return left.x != right.x || left.y != right.y || left.z != right.z || left.w != right.w;
        }

        public static fix4 operator -(fix4 value)
        {
            return new(-value.x, -value.y, -value.z, -value.w);
        }

        public static fix4 operator ++(fix4 value)
        {
            return new(++value.x, ++value.y, ++value.z, ++value.w);
        }

        public static fix4 operator --(fix4 value)
        {
            return new(--value.x, --value.y, --value.z, --value.w);
        }

        public static fix4 operator +(fix4 left, fix4 right)
        {
            return new(left.x + right.x, left.y + right.y, left.z + right.z, left.w + right.w);
        }

        public static fix4 operator -(fix4 left, fix4 right)
        {
            return new(left.x - right.x, left.y - right.y, left.z - right.z, left.w - right.w);
        }

        public static fix4 operator *(fix4 left, fix4 right)
        {
            return new(left.x * right.x, left.y * right.y, left.z * right.z, left.w * right.w);
        }

        public static fix4 operator /(fix4 left, fix4 right)
        {
            return new(left.x / right.x, left.y / right.y, left.z / right.z, left.w / right.w);
        }

        public static fix4 operator +(fix4 left, fix right)
        {
            return new(left.x + right, left.y + right, left.z + right, left.w + right);
        }

        public static fix4 operator +(fix left, fix4 right)
        {
            return new(left + right.x, left + right.y, left + right.z, left + right.w);
        }

        public static fix4 operator -(fix4 left, fix right)
        {
            return new(left.x - right, left.y - right, left.z - right, left.w - right);
        }

        public static fix4 operator -(fix left, fix4 right)
        {
            return new(left - right.x, left - right.y, left - right.z, left - right.w);
        }

        public static fix4 operator *(fix4 left, fix right)
        {
            return new(left.x * right, left.y * right, left.z * right, left.w * right);
        }

        public static fix4 operator *(fix left, fix4 right)
        {
            return new(left * right.x, left * right.y, left * right.z, left * right.w);
        }

        public static fix4 operator /(fix4 left, fix right)
        {
            return new(left.x / right, left.y / right, left.z / right, left.w / right);
        }

        public static fix4 operator /(fix left, fix4 right)
        {
            return new(left / right.x, left / right.y, left / right.z, left / right.w);
        }

        public static fix4 operator %(fix4 left, fix4 right)
        {
            return new(left.x % right.x, left.y % right.y, left.z % right.z, left.w % right.w);
        }

        public static fix4 operator %(fix4 left, fix right)
        {
            return new(left.x % right, left.y % right, left.z % right, left.w % right);
        }

        public static fix4 operator %(fix left, fix4 right)
        {
            return new(left % right.x, left % right.y, left % right.z, left % right.w);
        }

        public static fix4 operator <<(fix4 left, int right)
        {
            return new(left.x << right, left.y << right, left.z << right, left.w << right);
        }

        public static fix4 operator >>(fix4 left, int right)
        {
            return new(left.x >> right, left.y >> right, left.z >> right, left.w >> right);
        }

        public static bool4 operator <(fix4 left, fix4 right)
        {
            return new(left.x < right.x, left.y < right.y, left.z < right.z, left.w < right.w);
        }

        public static bool4 operator <(fix4 left, fix right)
        {
            return new(left.x < right, left.y < right, left.z < right, left.w < right);
        }

        public static bool4 operator <(fix left, fix4 right)
        {
            return new(left < right.x, left < right.y, left < right.z, left < right.w);
        }

        public static bool4 operator <=(fix4 left, fix4 right)
        {
            return new(left.x <= right.x, left.y <= right.y, left.z <= right.z, left.w <= right.w);
        }

        public static bool4 operator <=(fix4 left, fix right)
        {
            return new(left.x <= right, left.y <= right, left.z <= right, left.w <= right);
        }

        public static bool4 operator <=(fix left, fix4 right)
        {
            return new(left <= right.x, left <= right.y, left <= right.z, left <= right.w);
        }

        public static bool4 operator >(fix4 left, fix4 right)
        {
            return new(left.x > right.x, left.y > right.y, left.z > right.z, left.w > right.w);
        }

        public static bool4 operator >(fix4 left, fix right)
        {
            return new(left.x > right, left.y > right, left.z > right, left.w > right);
        }

        public static bool4 operator >(fix left, fix4 right)
        {
            return new(left > right.x, left > right.y, left > right.z, left > right.w);
        }

        public static bool4 operator >=(fix4 left, fix4 right)
        {
            return new(left.x >= right.x, left.y >= right.y, left.z >= right.z, left.w >= right.w);
        }

        public static bool4 operator >=(fix4 left, fix right)
        {
            return new(left.x >= right, left.y >= right, left.z >= right, left.w >= right);
        }

        public static bool4 operator >=(fix left, fix4 right)
        {
            return new(left >= right.x, left >= right.y, left >= right.z, left >= right.w);
        }

        public static explicit operator int4(fix4 value)
        {
            return new int4((int)value.x, (int)value.y, (int)value.z, (int)value.w);
        }

        public static explicit operator float4(fix4 value)
        {
            return new float4((float)value.x, (float)value.y, (float)value.z, (float)value.w);
        }

        public static explicit operator double4(fix4 value)
        {
            return new double4((double)value.x, (double)value.y, (double)value.z, (double)value.w);
        }
    }
}
