// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct fix4
    {

        public static fix4 Sin(fix4 value)
        {
            return new(Maths.Sin(value.x), Maths.Sin(value.y), Maths.Sin(value.z), Maths.Sin(value.w));
        }

        public static fix4 Cos(fix4 value)
        {
            return new(Maths.Cos(value.x), Maths.Cos(value.y), Maths.Cos(value.z), Maths.Cos(value.w));
        }

        public static fix4 Tan(fix4 value)
        {
            return new(Maths.Tan(value.x), Maths.Tan(value.y), Maths.Tan(value.z), Maths.Tan(value.w));
        }

        public static fix4 Asin(fix4 value)
        {
            return new(Maths.Asin(value.x), Maths.Asin(value.y), Maths.Asin(value.z), Maths.Asin(value.w));
        }

        public static fix4 Acos(fix4 value)
        {
            return new(Maths.Acos(value.x), Maths.Acos(value.y), Maths.Acos(value.z), Maths.Acos(value.w));
        }

        public static fix4 Atan(fix4 value)
        {
            return new(Maths.Atan(value.x), Maths.Atan(value.y), Maths.Atan(value.z), Maths.Atan(value.w));
        }

        public static fix4 Atan2(fix4 y, fix4 x)
        {
            return new(Maths.Atan2(y.x, x.x), Maths.Atan2(y.y, x.y), Maths.Atan2(y.z, x.z), Maths.Atan2(y.w, x.w));
        }

        public static fix4 Atan2(fix4 y, fix x)
        {
            return new(Maths.Atan2(y.x, x), Maths.Atan2(y.y, x), Maths.Atan2(y.z, x), Maths.Atan2(y.w, x));
        }

        public static fix4 Atan2(fix y, fix4 x)
        {
            return new(Maths.Atan2(y, x.x), Maths.Atan2(y, x.y), Maths.Atan2(y, x.z), Maths.Atan2(y, x.w));
        }
    }
}
