// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace DVG.Maths
{
    public partial struct float3
    {

        public static bool operator ==(float3 left, float3 right)
        {
            return left.x == right.x && left.y == right.y && left.z == right.z;
        }

        public static bool operator !=(float3 left, float3 right)
        {
            return left.x != right.x || left.y != right.y || left.z != right.z;
        }

        public static float3 operator +(float3 value)
        {
            return new(+value.x, +value.y, +value.z);
        }

        public static float3 operator -(float3 value)
        {
            return new(-value.x, -value.y, -value.z);
        }

        public static float3 operator ++(float3 value)
        {
            return new(++value.x, ++value.y, ++value.z);
        }

        public static float3 operator --(float3 value)
        {
            return new(--value.x, --value.y, --value.z);
        }

        public static float3 operator +(float3 left, float3 right)
        {
            return new(left.x + right.x, left.y + right.y, left.z + right.z);
        }

        public static float3 operator -(float3 left, float3 right)
        {
            return new(left.x - right.x, left.y - right.y, left.z - right.z);
        }

        public static float3 operator *(float3 left, float3 right)
        {
            return new(left.x * right.x, left.y * right.y, left.z * right.z);
        }

        public static float3 operator /(float3 left, float3 right)
        {
            return new(left.x / right.x, left.y / right.y, left.z / right.z);
        }

        public static float3 operator +(float3 left, float right)
        {
            return new(left.x + right, left.y + right, left.z + right);
        }

        public static float3 operator +(float left, float3 right)
        {
            return new(left + right.x, left + right.y, left + right.z);
        }

        public static float3 operator -(float3 left, float right)
        {
            return new(left.x - right, left.y - right, left.z - right);
        }

        public static float3 operator -(float left, float3 right)
        {
            return new(left - right.x, left - right.y, left - right.z);
        }

        public static float3 operator *(float3 left, float right)
        {
            return new(left.x * right, left.y * right, left.z * right);
        }

        public static float3 operator *(float left, float3 right)
        {
            return new(left * right.x, left * right.y, left * right.z);
        }

        public static float3 operator /(float3 left, float right)
        {
            return new(left.x / right, left.y / right, left.z / right);
        }

        public static float3 operator /(float left, float3 right)
        {
            return new(left / right.x, left / right.y, left / right.z);
        }

        public static float3 operator %(float3 left, float3 right)
        {
            return new(left.x % right.x, left.y % right.y, left.z % right.z);
        }

        public static float3 operator %(float3 left, float right)
        {
            return new(left.x % right, left.y % right, left.z % right);
        }

        public static float3 operator %(float left, float3 right)
        {
            return new(left % right.x, left % right.y, left % right.z);
        }

        public static bool3 operator <(float3 left, float3 right)
        {
            return new(left.x < right.x, left.y < right.y, left.z < right.z);
        }

        public static bool3 operator <(float3 left, float right)
        {
            return new(left.x < right, left.y < right, left.z < right);
        }

        public static bool3 operator <(float left, float3 right)
        {
            return new(left < right.x, left < right.y, left < right.z);
        }

        public static bool3 operator <=(float3 left, float3 right)
        {
            return new(left.x <= right.x, left.y <= right.y, left.z <= right.z);
        }

        public static bool3 operator <=(float3 left, float right)
        {
            return new(left.x <= right, left.y <= right, left.z <= right);
        }

        public static bool3 operator <=(float left, float3 right)
        {
            return new(left <= right.x, left <= right.y, left <= right.z);
        }

        public static bool3 operator >(float3 left, float3 right)
        {
            return new(left.x > right.x, left.y > right.y, left.z > right.z);
        }

        public static bool3 operator >(float3 left, float right)
        {
            return new(left.x > right, left.y > right, left.z > right);
        }

        public static bool3 operator >(float left, float3 right)
        {
            return new(left > right.x, left > right.y, left > right.z);
        }

        public static bool3 operator >=(float3 left, float3 right)
        {
            return new(left.x >= right.x, left.y >= right.y, left.z >= right.z);
        }

        public static bool3 operator >=(float3 left, float right)
        {
            return new(left.x >= right, left.y >= right, left.z >= right);
        }

        public static bool3 operator >=(float left, float3 right)
        {
            return new(left >= right.x, left >= right.y, left >= right.z);
        }

        public static implicit operator double3(float3 value)
        {
            return new double3((double)value.x, (double)value.y, (double)value.z);
        }

        public static explicit operator int3(float3 value)
        {
            return new int3((int)value.x, (int)value.y, (int)value.z);
        }

        public static explicit operator uint3(float3 value)
        {
            return new uint3((uint)value.x, (uint)value.y, (uint)value.z);
        }

        public static explicit operator fix3(float3 value)
        {
            return new fix3((fix)value.x, (fix)value.y, (fix)value.z);
        }
    }
}
