// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct float4x4
    {

        public static float4x4 Transpose(float4x4 value)
        {
            return new float4x4(value.M11, value.M21, value.M31, value.M41, value.M12, value.M22, value.M32, value.M42, value.M13, value.M23, value.M33, value.M43, value.M14, value.M24, value.M34, value.M44);
        }

        public static float Determinant(float4x4 value)
        {
            static float minor(float a11, float a12, float a13, float a21, float a22, float a23, float a31, float a32, float a33) =>
                a11 * (a22 * a33 - a23 * a32) - a12 * (a21 * a33 - a23 * a31) + a13 * (a21 * a32 - a22 * a31);
            return value.M11 * minor(value.M22, value.M23, value.M24, value.M32, value.M33, value.M34, value.M42, value.M43, value.M44)
                - value.M12 * minor(value.M21, value.M23, value.M24, value.M31, value.M33, value.M34, value.M41, value.M43, value.M44)
                + value.M13 * minor(value.M21, value.M22, value.M24, value.M31, value.M32, value.M34, value.M41, value.M42, value.M44)
                - value.M14 * minor(value.M21, value.M22, value.M23, value.M31, value.M32, value.M33, value.M41, value.M42, value.M43);
        }

        public static bool TryInverse(float4x4 value, out float4x4 result)
        {
            static float minor(float a11, float a12, float a13, float a21, float a22, float a23, float a31, float a32, float a33) =>
                a11 * (a22 * a33 - a23 * a32) - a12 * (a21 * a33 - a23 * a31) + a13 * (a21 * a32 - a22 * a31);
            var c11 = minor(value.M22, value.M23, value.M24, value.M32, value.M33, value.M34, value.M42, value.M43, value.M44);
            var c12 = -minor(value.M21, value.M23, value.M24, value.M31, value.M33, value.M34, value.M41, value.M43, value.M44);
            var c13 = minor(value.M21, value.M22, value.M24, value.M31, value.M32, value.M34, value.M41, value.M42, value.M44);
            var c14 = -minor(value.M21, value.M22, value.M23, value.M31, value.M32, value.M33, value.M41, value.M42, value.M43);
            var c21 = -minor(value.M12, value.M13, value.M14, value.M32, value.M33, value.M34, value.M42, value.M43, value.M44);
            var c22 = minor(value.M11, value.M13, value.M14, value.M31, value.M33, value.M34, value.M41, value.M43, value.M44);
            var c23 = -minor(value.M11, value.M12, value.M14, value.M31, value.M32, value.M34, value.M41, value.M42, value.M44);
            var c24 = minor(value.M11, value.M12, value.M13, value.M31, value.M32, value.M33, value.M41, value.M42, value.M43);
            var determinant = value.M11 * c11 + value.M12 * c12 + value.M13 * c13 + value.M14 * c14;
            if (Maths.Abs(determinant) <= 1e-8f)
            {
                result = default;
                return false;
            }
            var c31 = minor(value.M12, value.M13, value.M14, value.M22, value.M23, value.M24, value.M42, value.M43, value.M44);
            var c32 = -minor(value.M11, value.M13, value.M14, value.M21, value.M23, value.M24, value.M41, value.M43, value.M44);
            var c33 = minor(value.M11, value.M12, value.M14, value.M21, value.M22, value.M24, value.M41, value.M42, value.M44);
            var c34 = -minor(value.M11, value.M12, value.M13, value.M21, value.M22, value.M23, value.M41, value.M42, value.M43);
            var c41 = -minor(value.M12, value.M13, value.M14, value.M22, value.M23, value.M24, value.M32, value.M33, value.M34);
            var c42 = minor(value.M11, value.M13, value.M14, value.M21, value.M23, value.M24, value.M31, value.M33, value.M34);
            var c43 = -minor(value.M11, value.M12, value.M14, value.M21, value.M22, value.M24, value.M31, value.M32, value.M34);
            var c44 = minor(value.M11, value.M12, value.M13, value.M21, value.M22, value.M23, value.M31, value.M32, value.M33);
            var inverse = 1f / determinant;
            result = new float4x4(
                c11 * inverse, c21 * inverse, c31 * inverse, c41 * inverse,
                c12 * inverse, c22 * inverse, c32 * inverse, c42 * inverse,
                c13 * inverse, c23 * inverse, c33 * inverse, c43 * inverse,
                c14 * inverse, c24 * inverse, c34 * inverse, c44 * inverse);
            return true;
        }

        public static float4x4 Inverse(float4x4 value)
        {
            return TryInverse(value, out var result) ? result : identity;
        }
    }
}
