// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace DVG.Maths
{
    public partial struct float2
    {

        public static float2 Select(float2 falseValue, float2 trueValue, bool2 mask)
        {
            return new(mask.x ? trueValue.x : falseValue.x, mask.y ? trueValue.y : falseValue.y);
        }

        public static float2 Select(float2 falseValue, float2 trueValue, bool mask)
        {
            return new(mask ? trueValue.x : falseValue.x, mask ? trueValue.y : falseValue.y);
        }

        public static float2 Select(float falseValue, float trueValue, bool2 mask)
        {
            return new(mask.x ? trueValue : falseValue, mask.y ? trueValue : falseValue);
        }

        public static bool2 Equal(float2 a, float2 b)
        {
            return new(a.x == b.x, a.y == b.y);
        }

        public static bool2 Equal(float2 a, float b)
        {
            return new(a.x == b, a.y == b);
        }

        public static bool2 Equal(float a, float2 b)
        {
            return new(a == b.x, a == b.y);
        }

        public static bool2 NotEqual(float2 a, float2 b)
        {
            return new(a.x != b.x, a.y != b.y);
        }

        public static bool2 NotEqual(float2 a, float b)
        {
            return new(a.x != b, a.y != b);
        }

        public static bool2 NotEqual(float a, float2 b)
        {
            return new(a != b.x, a != b.y);
        }

        public static bool2 LessThan(float2 a, float2 b)
        {
            return new(a.x < b.x, a.y < b.y);
        }

        public static bool2 LessThan(float2 a, float b)
        {
            return new(a.x < b, a.y < b);
        }

        public static bool2 LessThan(float a, float2 b)
        {
            return new(a < b.x, a < b.y);
        }

        public static bool2 LessThanOrEqual(float2 a, float2 b)
        {
            return new(a.x <= b.x, a.y <= b.y);
        }

        public static bool2 LessThanOrEqual(float2 a, float b)
        {
            return new(a.x <= b, a.y <= b);
        }

        public static bool2 LessThanOrEqual(float a, float2 b)
        {
            return new(a <= b.x, a <= b.y);
        }

        public static bool2 GreaterThan(float2 a, float2 b)
        {
            return new(a.x > b.x, a.y > b.y);
        }

        public static bool2 GreaterThan(float2 a, float b)
        {
            return new(a.x > b, a.y > b);
        }

        public static bool2 GreaterThan(float a, float2 b)
        {
            return new(a > b.x, a > b.y);
        }

        public static bool2 GreaterThanOrEqual(float2 a, float2 b)
        {
            return new(a.x >= b.x, a.y >= b.y);
        }

        public static bool2 GreaterThanOrEqual(float2 a, float b)
        {
            return new(a.x >= b, a.y >= b);
        }

        public static bool2 GreaterThanOrEqual(float a, float2 b)
        {
            return new(a >= b.x, a >= b.y);
        }

        public static bool2 IsNaN(float2 value)
        {
            return new(Maths.IsNaN(value.x), Maths.IsNaN(value.y));
        }

        public static bool2 IsInfinity(float2 value)
        {
            return new(Maths.IsInfinity(value.x), Maths.IsInfinity(value.y));
        }

        public static bool2 IsFinite(float2 value)
        {
            return new(Maths.IsFinite(value.x), Maths.IsFinite(value.y));
        }
    }
}
