// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct float3
    {

        public static float3 Min(float3 a, float3 b)
        {
            return new(Maths.Min(a.x, b.x), Maths.Min(a.y, b.y), Maths.Min(a.z, b.z));
        }

        public static float3 Min(float3 a, float b)
        {
            return new(Maths.Min(a.x, b), Maths.Min(a.y, b), Maths.Min(a.z, b));
        }

        public static float3 Min(float a, float3 b)
        {
            return new(Maths.Min(a, b.x), Maths.Min(a, b.y), Maths.Min(a, b.z));
        }

        public static float3 Max(float3 a, float3 b)
        {
            return new(Maths.Max(a.x, b.x), Maths.Max(a.y, b.y), Maths.Max(a.z, b.z));
        }

        public static float3 Max(float3 a, float b)
        {
            return new(Maths.Max(a.x, b), Maths.Max(a.y, b), Maths.Max(a.z, b));
        }

        public static float3 Max(float a, float3 b)
        {
            return new(Maths.Max(a, b.x), Maths.Max(a, b.y), Maths.Max(a, b.z));
        }

        public static float3 Clamp(float3 value, float min, float max)
        {
            return new(Maths.Clamp(value.x, min, max), Maths.Clamp(value.y, min, max), Maths.Clamp(value.z, min, max));
        }

        public static float3 Clamp(float3 value, float3 min, float3 max)
        {
            return new(Maths.Clamp(value.x, min.x, max.x), Maths.Clamp(value.y, min.y, max.y), Maths.Clamp(value.z, min.z, max.z));
        }

        public static float3 Abs(float3 value)
        {
            return new(Maths.Abs(value.x), Maths.Abs(value.y), Maths.Abs(value.z));
        }

        public static float3 Sign(float3 value)
        {
            return new(Maths.Sign(value.x), Maths.Sign(value.y), Maths.Sign(value.z));
        }

        public static float Sum(float3 value)
        {
            return value.x + value.y + value.z;
        }

        public static float3 Lerp(float3 a, float3 b, float t)
        {
            return new(Maths.Lerp(a.x, b.x, t), Maths.Lerp(a.y, b.y, t), Maths.Lerp(a.z, b.z, t));
        }

        public static float3 Lerp(float3 a, float3 b, float3 t)
        {
            return new(Maths.Lerp(a.x, b.x, t.x), Maths.Lerp(a.y, b.y, t.y), Maths.Lerp(a.z, b.z, t.z));
        }

        public static float3 InvLerp(float3 edge0, float3 edge1, float3 value)
        {
            return new(Maths.InvLerp(edge0.x, edge1.x, value.x), Maths.InvLerp(edge0.y, edge1.y, value.y), Maths.InvLerp(edge0.z, edge1.z, value.z));
        }

        public static float3 InvLerp(float3 edge0, float3 edge1, float value)
        {
            return new(Maths.InvLerp(edge0.x, edge1.x, value), Maths.InvLerp(edge0.y, edge1.y, value), Maths.InvLerp(edge0.z, edge1.z, value));
        }

        public static float3 SmoothStep(float3 edge0, float3 edge1, float3 value)
        {
            return new(Maths.SmoothStep(edge0.x, edge1.x, value.x), Maths.SmoothStep(edge0.y, edge1.y, value.y), Maths.SmoothStep(edge0.z, edge1.z, value.z));
        }

        public static float3 SmoothStep(float edge0, float edge1, float3 value)
        {
            return new(Maths.SmoothStep(edge0, edge1, value.x), Maths.SmoothStep(edge0, edge1, value.y), Maths.SmoothStep(edge0, edge1, value.z));
        }

        public static float3 Step(float3 edge, float3 value)
        {
            return new(Maths.Step(edge.x, value.x), Maths.Step(edge.y, value.y), Maths.Step(edge.z, value.z));
        }

        public static float3 Step(float edge, float3 value)
        {
            return new(Maths.Step(edge, value.x), Maths.Step(edge, value.y), Maths.Step(edge, value.z));
        }

        public static float3 Saturate(float3 value)
        {
            return new(Maths.Saturate(value.x), Maths.Saturate(value.y), Maths.Saturate(value.z));
        }

        public static float3 Fma(float3 a, float3 b, float3 c)
        {
            return new(Maths.Fma(a.x, b.x, c.x), Maths.Fma(a.y, b.y, c.y), Maths.Fma(a.z, b.z, c.z));
        }

        public static float3 Remap(float3 value, float3 sourceFrom, float3 sourceTo, float3 targetFrom, float3 targetTo)
        {
            return new(Maths.Remap(value.x, sourceFrom.x, sourceTo.x, targetFrom.x, targetTo.x), Maths.Remap(value.y, sourceFrom.y, sourceTo.y, targetFrom.y, targetTo.y), Maths.Remap(value.z, sourceFrom.z, sourceTo.z, targetFrom.z, targetTo.z));
        }

        public static float3 Floor(float3 value)
        {
            return new(Maths.Floor(value.x), Maths.Floor(value.y), Maths.Floor(value.z));
        }

        public static float3 Ceil(float3 value)
        {
            return new(Maths.Ceil(value.x), Maths.Ceil(value.y), Maths.Ceil(value.z));
        }

        public static float3 Round(float3 value)
        {
            return new(Maths.Round(value.x), Maths.Round(value.y), Maths.Round(value.z));
        }

        public static float3 Truncate(float3 value)
        {
            return new(Maths.Truncate(value.x), Maths.Truncate(value.y), Maths.Truncate(value.z));
        }

        public static float3 Fract(float3 value)
        {
            return new(Maths.Fract(value.x), Maths.Fract(value.y), Maths.Fract(value.z));
        }

        public static float3 Radians(float3 value)
        {
            return new(Maths.Radians(value.x), Maths.Radians(value.y), Maths.Radians(value.z));
        }

        public static float3 Degrees(float3 value)
        {
            return new(Maths.Degrees(value.x), Maths.Degrees(value.y), Maths.Degrees(value.z));
        }
    }
}
