// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    /// <summary>A vector of type float with 4 components.</summary>
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    [System.Runtime.Serialization.DataContract]
    public partial struct float4 : IEquatable<float4>, IComparable<float4>
    {

        [System.Runtime.Serialization.DataMember(Order = 0)]
        public float x;

        [System.Runtime.Serialization.DataMember(Order = 1)]
        public float y;

        [System.Runtime.Serialization.DataMember(Order = 2)]
        public float z;

        [System.Runtime.Serialization.DataMember(Order = 3)]
        public float w;

        public static readonly float4 zero = new float4(0f, 0f, 0f, 0f);

        public float4(float x, float y, float z, float w)
        {
            this.x = x;
            this.y = y;
            this.z = z;
            this.w = w;
        }

        public float4(float value)
        {
            x = value;
            y = value;
            z = value;
            w = value;
        }

        public float4(float2 value)
        {
            x = value.x;
            y = value.y;
            z = 0f;
            w = 0f;
        }

        public float4(float3 value)
        {
            x = value.x;
            y = value.y;
            z = value.z;
            w = 0f;
        }

        public float4(float4 value)
        {
            x = value.x;
            y = value.y;
            z = value.z;
            w = value.w;
        }

        public float4(float x, float y, float2 zw)
        {
            this.x = x;
            this.y = y;
            this.z = zw.x;
            this.w = zw.y;
        }

        public float4(float x, float2 yz, float w)
        {
            this.x = x;
            this.y = yz.x;
            this.z = yz.y;
            this.w = w;
        }

        public float4(float x, float3 yzw)
        {
            this.x = x;
            this.y = yzw.x;
            this.z = yzw.y;
            this.w = yzw.z;
        }

        public float4(float2 xy, float z, float w)
        {
            this.x = xy.x;
            this.y = xy.y;
            this.z = z;
            this.w = w;
        }

        public float4(float2 xy, float2 zw)
        {
            this.x = xy.x;
            this.y = xy.y;
            this.z = zw.x;
            this.w = zw.y;
        }

        public float4(float3 xyz, float w)
        {
            this.x = xyz.x;
            this.y = xyz.y;
            this.z = xyz.z;
            this.w = w;
        }

        public float this[int index]
        {
            get
            {
                if ((uint)index >= Count)
                    throw new ArgumentOutOfRangeException(nameof(index));
                return Unsafe.Add(ref x, index);
            }
            set
            {
                if ((uint)index >= Count)
                    throw new ArgumentOutOfRangeException(nameof(index));
                Unsafe.Add(ref x, index) = value;
            }
        }

        public int Count => 4;

        public bool Equals(float4 other)
        {
            return x.Equals(other.x) && y.Equals(other.y) && z.Equals(other.z) && w.Equals(other.w);
        }

        public override bool Equals(object obj)
        {
            return obj is float4 other && Equals(other);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                var hash = 17;
                hash = hash * 31 + x.GetHashCode();
                hash = hash * 31 + y.GetHashCode();
                hash = hash * 31 + z.GetHashCode();
                hash = hash * 31 + w.GetHashCode();
                return hash;
            }
        }

        public int CompareTo(float4 other)
        {
            var xComparison = x.CompareTo(other.x);
            if (xComparison != 0) return xComparison;
            var yComparison = y.CompareTo(other.y);
            if (yComparison != 0) return yComparison;
            var zComparison = z.CompareTo(other.z);
            if (zComparison != 0) return zComparison;
            var wComparison = w.CompareTo(other.w);
            if (wComparison != 0) return wComparison;
            return 0;
        }

        public override string ToString()
        {
            return FormattableString.Invariant($"{x}, {y}, {z}, {w}");
        }

        public static float4 Parse(string value)
        {
            value = value.Trim();
            if (value.Length >= 2 && value[0] == '[' && value[value.Length - 1] == ']')
                value = value.Substring(1, value.Length - 2);
            var values = value.Split(',');
            if (values.Length != 4)
                throw new FormatException("Expected 4 vector components.");
            return new(float.Parse(values[0].Trim(), System.Globalization.CultureInfo.InvariantCulture), float.Parse(values[1].Trim(), System.Globalization.CultureInfo.InvariantCulture), float.Parse(values[2].Trim(), System.Globalization.CultureInfo.InvariantCulture), float.Parse(values[3].Trim(), System.Globalization.CultureInfo.InvariantCulture));
        }

        public static float4 Parse(string value, IFormatProvider format)
        {
            value = value.Trim();
            if (value.Length >= 2 && value[0] == '[' && value[value.Length - 1] == ']')
                value = value.Substring(1, value.Length - 2);
            var values = value.Split(',');
            if (values.Length != 4)
                throw new FormatException("Expected 4 vector components.");
            return new(float.Parse(values[0].Trim(), format), float.Parse(values[1].Trim(), format), float.Parse(values[2].Trim(), format), float.Parse(values[3].Trim(), format));
        }
    }
}
