// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace KibiHex
{
    public partial struct float4
    {

        public static float Dot(float4 a, float4 b)
        {
            return a.x * b.x + a.y * b.y + a.z * b.z + a.w * b.w;
        }

        public static float SqrLength(float4 value)
        {
            return value.x * value.x + value.y * value.y + value.z * value.z + value.w * value.w;
        }

        public static float Length(float4 value)
        {
            return Maths.Sqrt(SqrLength(value));
        }

        public static float Distance(float4 a, float4 b)
        {
            return Length(a - b);
        }

        public static float SqrDistance(float4 a, float4 b)
        {
            return SqrLength(a - b);
        }

        public static float4 Normalize(float4 value)
        {
            return value / Length(value);
        }

        public static float4 NormalizeSafe(float4 value)
        {
            var sqrLength = SqrLength(value);
            return sqrLength <= 1.17549435E-38f ? zero : value * Maths.InverseSqrt(sqrLength);
        }

        public static float4 NormalizeSafe(float4 value, float4 fallback)
        {
            var sqrLength = SqrLength(value);
            return sqrLength <= 1.17549435E-38f ? fallback : value * Maths.InverseSqrt(sqrLength);
        }

        public static float4 FaceForward(float4 N, float4 I, float4 Nref)
        {
            return Dot(Nref, I) < 0 ? N : -N;
        }

        public static float4 Reflect(float4 I, float4 N)
        {
            return I - 2 * Dot(N, I) * N;
        }

        public static float4 Refract(float4 I, float4 N, float eta)
        {
            var dNI = Dot(N, I);
            var k = 1 - eta * eta * (1 - dNI * dNI);
            if (k < 0) return zero;
            return eta * I - (eta * dNI + Maths.Sqrt(k)) * N;
        }

        public static float4 Project(float4 value, float4 onto)
        {
            return onto * (Dot(value, onto) / SqrLength(onto));
        }

        public static float4 ProjectSafe(float4 value, float4 onto)
        {
            var denominator = SqrLength(onto);
            return denominator == 0 ? zero : onto * (Dot(value, onto) / denominator);
        }

        public static float4 ClampLength(float4 value, float maxLength)
        {
            maxLength = Maths.Max(maxLength, 0);
            var sqrLength = SqrLength(value);
            if (sqrLength > maxLength * maxLength)
            {
                return value * maxLength * Maths.InverseSqrt(sqrLength);
            }
            return value;
        }

        public static float4 MoveTowards(float4 current, float4 target, float maxDelta)
        {
            maxDelta = Maths.Max(maxDelta, 0);
            var delta = target - current;
            var sqrDistance = SqrLength(delta);
            if (sqrDistance == 0 || sqrDistance <= maxDelta * maxDelta)
                return target;
            return current + delta * maxDelta * Maths.InverseSqrt(sqrDistance);
        }

        public static float4 SmoothDamp(float4 source, float4 target, ref float4 velocity, float smoothTime, float deltaTime)
        {
            return new(Maths.SmoothDamp(source.x, target.x, ref velocity.x, smoothTime, deltaTime), Maths.SmoothDamp(source.y, target.y, ref velocity.y, smoothTime, deltaTime), Maths.SmoothDamp(source.z, target.z, ref velocity.z, smoothTime, deltaTime), Maths.SmoothDamp(source.w, target.w, ref velocity.w, smoothTime, deltaTime));
        }
    }
}
