// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace DVG.Maths
{
    public partial struct float4
    {

        public static float4 Sin(float4 value)
        {
            return new(Maths.Sin(value.x), Maths.Sin(value.y), Maths.Sin(value.z), Maths.Sin(value.w));
        }

        public static float4 Cos(float4 value)
        {
            return new(Maths.Cos(value.x), Maths.Cos(value.y), Maths.Cos(value.z), Maths.Cos(value.w));
        }

        public static float4 Tan(float4 value)
        {
            return new(Maths.Tan(value.x), Maths.Tan(value.y), Maths.Tan(value.z), Maths.Tan(value.w));
        }

        public static float4 Asin(float4 value)
        {
            return new(Maths.Asin(value.x), Maths.Asin(value.y), Maths.Asin(value.z), Maths.Asin(value.w));
        }

        public static float4 Acos(float4 value)
        {
            return new(Maths.Acos(value.x), Maths.Acos(value.y), Maths.Acos(value.z), Maths.Acos(value.w));
        }

        public static float4 Atan(float4 value)
        {
            return new(Maths.Atan(value.x), Maths.Atan(value.y), Maths.Atan(value.z), Maths.Atan(value.w));
        }

        public static float4 Atan2(float4 y, float4 x)
        {
            return new(Maths.Atan2(y.x, x.x), Maths.Atan2(y.y, x.y), Maths.Atan2(y.z, x.z), Maths.Atan2(y.w, x.w));
        }

        public static float4 Atan2(float4 y, float x)
        {
            return new(Maths.Atan2(y.x, x), Maths.Atan2(y.y, x), Maths.Atan2(y.z, x), Maths.Atan2(y.w, x));
        }

        public static float4 Atan2(float y, float4 x)
        {
            return new(Maths.Atan2(y, x.x), Maths.Atan2(y, x.y), Maths.Atan2(y, x.z), Maths.Atan2(y, x.w));
        }

        public static float4 Sinh(float4 value)
        {
            return new(Maths.Sinh(value.x), Maths.Sinh(value.y), Maths.Sinh(value.z), Maths.Sinh(value.w));
        }

        public static float4 Cosh(float4 value)
        {
            return new(Maths.Cosh(value.x), Maths.Cosh(value.y), Maths.Cosh(value.z), Maths.Cosh(value.w));
        }

        public static float4 Tanh(float4 value)
        {
            return new(Maths.Tanh(value.x), Maths.Tanh(value.y), Maths.Tanh(value.z), Maths.Tanh(value.w));
        }

        public static float4 Asinh(float4 value)
        {
            return new(Maths.Asinh(value.x), Maths.Asinh(value.y), Maths.Asinh(value.z), Maths.Asinh(value.w));
        }

        public static float4 Acosh(float4 value)
        {
            return new(Maths.Acosh(value.x), Maths.Acosh(value.y), Maths.Acosh(value.z), Maths.Acosh(value.w));
        }

        public static float4 Atanh(float4 value)
        {
            return new(Maths.Atanh(value.x), Maths.Atanh(value.y), Maths.Atanh(value.z), Maths.Atanh(value.w));
        }
    }
}
