// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct float3
    {

        public static float3 Select(float3 falseValue, float3 trueValue, bool3 mask)
        {
            return new(mask.x ? trueValue.x : falseValue.x, mask.y ? trueValue.y : falseValue.y, mask.z ? trueValue.z : falseValue.z);
        }

        public static float3 Select(float3 falseValue, float3 trueValue, bool mask)
        {
            return new(mask ? trueValue.x : falseValue.x, mask ? trueValue.y : falseValue.y, mask ? trueValue.z : falseValue.z);
        }

        public static float3 Select(float falseValue, float trueValue, bool3 mask)
        {
            return new(mask.x ? trueValue : falseValue, mask.y ? trueValue : falseValue, mask.z ? trueValue : falseValue);
        }

        public static bool3 Equal(float3 a, float3 b)
        {
            return new(a.x == b.x, a.y == b.y, a.z == b.z);
        }

        public static bool3 Equal(float3 a, float b)
        {
            return new(a.x == b, a.y == b, a.z == b);
        }

        public static bool3 Equal(float a, float3 b)
        {
            return new(a == b.x, a == b.y, a == b.z);
        }

        public static bool3 NotEqual(float3 a, float3 b)
        {
            return new(a.x != b.x, a.y != b.y, a.z != b.z);
        }

        public static bool3 NotEqual(float3 a, float b)
        {
            return new(a.x != b, a.y != b, a.z != b);
        }

        public static bool3 NotEqual(float a, float3 b)
        {
            return new(a != b.x, a != b.y, a != b.z);
        }

        public static bool3 LessThan(float3 a, float3 b)
        {
            return new(a.x < b.x, a.y < b.y, a.z < b.z);
        }

        public static bool3 LessThan(float3 a, float b)
        {
            return new(a.x < b, a.y < b, a.z < b);
        }

        public static bool3 LessThan(float a, float3 b)
        {
            return new(a < b.x, a < b.y, a < b.z);
        }

        public static bool3 LessThanOrEqual(float3 a, float3 b)
        {
            return new(a.x <= b.x, a.y <= b.y, a.z <= b.z);
        }

        public static bool3 LessThanOrEqual(float3 a, float b)
        {
            return new(a.x <= b, a.y <= b, a.z <= b);
        }

        public static bool3 LessThanOrEqual(float a, float3 b)
        {
            return new(a <= b.x, a <= b.y, a <= b.z);
        }

        public static bool3 GreaterThan(float3 a, float3 b)
        {
            return new(a.x > b.x, a.y > b.y, a.z > b.z);
        }

        public static bool3 GreaterThan(float3 a, float b)
        {
            return new(a.x > b, a.y > b, a.z > b);
        }

        public static bool3 GreaterThan(float a, float3 b)
        {
            return new(a > b.x, a > b.y, a > b.z);
        }

        public static bool3 GreaterThanOrEqual(float3 a, float3 b)
        {
            return new(a.x >= b.x, a.y >= b.y, a.z >= b.z);
        }

        public static bool3 GreaterThanOrEqual(float3 a, float b)
        {
            return new(a.x >= b, a.y >= b, a.z >= b);
        }

        public static bool3 GreaterThanOrEqual(float a, float3 b)
        {
            return new(a >= b.x, a >= b.y, a >= b.z);
        }

        public static bool3 IsNaN(float3 value)
        {
            return new(Maths.IsNaN(value.x), Maths.IsNaN(value.y), Maths.IsNaN(value.z));
        }

        public static bool3 IsInfinity(float3 value)
        {
            return new(Maths.IsInfinity(value.x), Maths.IsInfinity(value.y), Maths.IsInfinity(value.z));
        }

        public static bool3 IsFinite(float3 value)
        {
            return new(Maths.IsFinite(value.x), Maths.IsFinite(value.y), Maths.IsFinite(value.z));
        }
    }
}
