// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace KibiHex
{
    public partial struct float3
    {

        public static float Dot(float3 a, float3 b)
        {
            return a.x * b.x + a.y * b.y + a.z * b.z;
        }

        public static float SqrLength(float3 value)
        {
            return value.x * value.x + value.y * value.y + value.z * value.z;
        }

        public static float Length(float3 value)
        {
            return Maths.Sqrt(SqrLength(value));
        }

        public static float Distance(float3 a, float3 b)
        {
            return Length(a - b);
        }

        public static float SqrDistance(float3 a, float3 b)
        {
            return SqrLength(a - b);
        }

        public static float3 Normalize(float3 value)
        {
            return value / Length(value);
        }

        public static float3 NormalizeSafe(float3 value)
        {
            var sqrLength = SqrLength(value);
            return sqrLength <= 1.17549435E-38f ? zero : value * Maths.InverseSqrt(sqrLength);
        }

        public static float3 NormalizeSafe(float3 value, float3 fallback)
        {
            var sqrLength = SqrLength(value);
            return sqrLength <= 1.17549435E-38f ? fallback : value * Maths.InverseSqrt(sqrLength);
        }

        public static float3 FaceForward(float3 N, float3 I, float3 Nref)
        {
            return Dot(Nref, I) < 0 ? N : -N;
        }

        public static float3 Reflect(float3 I, float3 N)
        {
            return I - 2 * Dot(N, I) * N;
        }

        public static float3 Refract(float3 I, float3 N, float eta)
        {
            var dNI = Dot(N, I);
            var k = 1 - eta * eta * (1 - dNI * dNI);
            if (k < 0) return zero;
            return eta * I - (eta * dNI + Maths.Sqrt(k)) * N;
        }

        public static float3 Project(float3 value, float3 onto)
        {
            return onto * (Dot(value, onto) / SqrLength(onto));
        }

        public static float3 ProjectSafe(float3 value, float3 onto)
        {
            var denominator = SqrLength(onto);
            return denominator == 0 ? zero : onto * (Dot(value, onto) / denominator);
        }

        public static float3 ClampLength(float3 value, float maxLength)
        {
            maxLength = Maths.Max(maxLength, 0);
            var sqrLength = SqrLength(value);
            if (sqrLength > maxLength * maxLength)
            {
                return value * maxLength * Maths.InverseSqrt(sqrLength);
            }
            return value;
        }

        public static float3 MoveTowards(float3 current, float3 target, float maxDelta)
        {
            maxDelta = Maths.Max(maxDelta, 0);
            var delta = target - current;
            var sqrDistance = SqrLength(delta);
            if (sqrDistance == 0 || sqrDistance <= maxDelta * maxDelta)
                return target;
            return current + delta * maxDelta * Maths.InverseSqrt(sqrDistance);
        }

        public static float3 SmoothDamp(float3 source, float3 target, ref float3 velocity, float smoothTime, float deltaTime)
        {
            return new(Maths.SmoothDamp(source.x, target.x, ref velocity.x, smoothTime, deltaTime), Maths.SmoothDamp(source.y, target.y, ref velocity.y, smoothTime, deltaTime), Maths.SmoothDamp(source.z, target.z, ref velocity.z, smoothTime, deltaTime));
        }

        public static float3 Cross(float3 a, float3 b)
        {
            return new(a.y * b.z - a.z * b.y, a.z * b.x - a.x * b.z, a.x * b.y - a.y * b.x);
        }
    }
}
