// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    /// <summary>A column-major 4x4 matrix represented by four float4 columns.</summary>
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    [System.Runtime.Serialization.DataContract]
    public partial struct float4x4 : IEquatable<float4x4>
    {

        /// <summary>First column.</summary>
        public float4 c0;

        /// <summary>Second column.</summary>
        public float4 c1;

        /// <summary>Third column.</summary>
        public float4 c2;

        /// <summary>Fourth column.</summary>
        public float4 c3;

        /// <summary>A matrix whose components are all zero.</summary>
        public static readonly float4x4 zero = new float4x4(float4.zero, float4.zero, float4.zero, float4.zero);

        /// <summary>The identity matrix.</summary>
        public static readonly float4x4 identity = new float4x4(1f, 0f, 0f, 0f, 0f, 1f, 0f, 0f, 0f, 0f, 1f, 0f, 0f, 0f, 0f, 1f);

        /// <summary>Creates a matrix from its four columns.</summary>
        public float4x4(float4 c0, float4 c1, float4 c2, float4 c3)
        {
            this.c0 = c0;
            this.c1 = c1;
            this.c2 = c2;
            this.c3 = c3;
        }

        /// <summary>Creates a matrix from row and column named components in mathematical order.</summary>
        public float4x4(float m11, float m12, float m13, float m14, float m21, float m22, float m23, float m24, float m31, float m32, float m33, float m34, float m41, float m42, float m43, float m44)
        {
            c0 = new float4(m11, m21, m31, m41);
            c1 = new float4(m12, m22, m32, m42);
            c2 = new float4(m13, m23, m33, m43);
            c3 = new float4(m14, m24, m34, m44);
        }

        public static float4x4 Identity => identity;

        /// <summary>Returns a column using zero-based indexing.</summary>
        public float4 GetColumn(int index)
        {
            return index switch { 0 => c0, 1 => c1, 2 => c2, 3 => c3, _ => throw new ArgumentOutOfRangeException(nameof(index)) };
        }

        /// <summary>Returns a row using zero-based indexing.</summary>
        public float4 GetRow(int index)
        {
            return index switch { 0 => new float4(M11, M12, M13, M14), 1 => new float4(M21, M22, M23, M24), 2 => new float4(M31, M32, M33, M34), 3 => new float4(M41, M42, M43, M44), _ => throw new ArgumentOutOfRangeException(nameof(index)) };
        }

        public float GetElement(int column, int row)
        {
            return GetColumn(column)[row];
        }

        public void SetElement(int column, int row, float value)
        {
            if ((uint)column >= 4u || (uint)row >= 4u) throw new ArgumentOutOfRangeException();
            var columnValue = GetColumn(column);
            columnValue[row] = value;
            switch (column) { case 0: c0 = columnValue; break; case 1: c1 = columnValue; break; case 2: c2 = columnValue; break; default: c3 = columnValue; break; }
        }

        public bool Equals(float4x4 other)
        {
            return this == other;
        }

        public override bool Equals(object obj)
        {
            return obj is float4x4 other && Equals(other);
        }

        public override int GetHashCode()
        {
            unchecked { var hash = 17; hash = hash * 31 + c0.GetHashCode(); hash = hash * 31 + c1.GetHashCode(); hash = hash * 31 + c2.GetHashCode(); hash = hash * 31 + c3.GetHashCode(); return hash; }
        }

        public override string ToString()
        {
            return FormattableString.Invariant($"[{M11}, {M12}, {M13}, {M14}; {M21}, {M22}, {M23}, {M24}; {M31}, {M32}, {M33}, {M34}; {M41}, {M42}, {M43}, {M44}]");
        }

        public float M11
        {
            get => c0.x;
            set => c0.x = value;
        }

        public float M12
        {
            get => c1.x;
            set => c1.x = value;
        }

        public float M13
        {
            get => c2.x;
            set => c2.x = value;
        }

        public float M14
        {
            get => c3.x;
            set => c3.x = value;
        }

        public float M21
        {
            get => c0.y;
            set => c0.y = value;
        }

        public float M22
        {
            get => c1.y;
            set => c1.y = value;
        }

        public float M23
        {
            get => c2.y;
            set => c2.y = value;
        }

        public float M24
        {
            get => c3.y;
            set => c3.y = value;
        }

        public float M31
        {
            get => c0.z;
            set => c0.z = value;
        }

        public float M32
        {
            get => c1.z;
            set => c1.z = value;
        }

        public float M33
        {
            get => c2.z;
            set => c2.z = value;
        }

        public float M34
        {
            get => c3.z;
            set => c3.z = value;
        }

        public float M41
        {
            get => c0.w;
            set => c0.w = value;
        }

        public float M42
        {
            get => c1.w;
            set => c1.w = value;
        }

        public float M43
        {
            get => c2.w;
            set => c2.w = value;
        }

        public float M44
        {
            get => c3.w;
            set => c3.w = value;
        }
    }
}
