// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace KibiHex
{
    public partial struct int2
    {

        public static int2 Select(int2 falseValue, int2 trueValue, bool2 mask)
        {
            return new(mask.x ? trueValue.x : falseValue.x, mask.y ? trueValue.y : falseValue.y);
        }

        public static int2 Select(int2 falseValue, int2 trueValue, bool mask)
        {
            return new(mask ? trueValue.x : falseValue.x, mask ? trueValue.y : falseValue.y);
        }

        public static int2 Select(int falseValue, int trueValue, bool2 mask)
        {
            return new(mask.x ? trueValue : falseValue, mask.y ? trueValue : falseValue);
        }

        public static bool2 Equal(int2 a, int2 b)
        {
            return new(a.x == b.x, a.y == b.y);
        }

        public static bool2 Equal(int2 a, int b)
        {
            return new(a.x == b, a.y == b);
        }

        public static bool2 Equal(int a, int2 b)
        {
            return new(a == b.x, a == b.y);
        }

        public static bool2 NotEqual(int2 a, int2 b)
        {
            return new(a.x != b.x, a.y != b.y);
        }

        public static bool2 NotEqual(int2 a, int b)
        {
            return new(a.x != b, a.y != b);
        }

        public static bool2 NotEqual(int a, int2 b)
        {
            return new(a != b.x, a != b.y);
        }

        public static bool2 LessThan(int2 a, int2 b)
        {
            return new(a.x < b.x, a.y < b.y);
        }

        public static bool2 LessThan(int2 a, int b)
        {
            return new(a.x < b, a.y < b);
        }

        public static bool2 LessThan(int a, int2 b)
        {
            return new(a < b.x, a < b.y);
        }

        public static bool2 LessThanOrEqual(int2 a, int2 b)
        {
            return new(a.x <= b.x, a.y <= b.y);
        }

        public static bool2 LessThanOrEqual(int2 a, int b)
        {
            return new(a.x <= b, a.y <= b);
        }

        public static bool2 LessThanOrEqual(int a, int2 b)
        {
            return new(a <= b.x, a <= b.y);
        }

        public static bool2 GreaterThan(int2 a, int2 b)
        {
            return new(a.x > b.x, a.y > b.y);
        }

        public static bool2 GreaterThan(int2 a, int b)
        {
            return new(a.x > b, a.y > b);
        }

        public static bool2 GreaterThan(int a, int2 b)
        {
            return new(a > b.x, a > b.y);
        }

        public static bool2 GreaterThanOrEqual(int2 a, int2 b)
        {
            return new(a.x >= b.x, a.y >= b.y);
        }

        public static bool2 GreaterThanOrEqual(int2 a, int b)
        {
            return new(a.x >= b, a.y >= b);
        }

        public static bool2 GreaterThanOrEqual(int a, int2 b)
        {
            return new(a >= b.x, a >= b.y);
        }
    }
}
