// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    /// <summary>A vector of type int with 2 components.</summary>
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    [System.Runtime.Serialization.DataContract]
    public partial struct int2 : IEquatable<int2>, IComparable<int2>
    {

        [System.Runtime.Serialization.DataMember(Order = 0)]
        public int x;

        [System.Runtime.Serialization.DataMember(Order = 1)]
        public int y;

        public static readonly int2 zero = new int2(0, 0);

        public int2(int x, int y)
        {
            this.x = x;
            this.y = y;
        }

        public int2(int value)
        {
            x = value;
            y = value;
        }

        public int2(int2 value)
        {
            x = value.x;
            y = value.y;
        }

        public int2(int3 value)
        {
            x = value.x;
            y = value.y;
        }

        public int2(int4 value)
        {
            x = value.x;
            y = value.y;
        }

        public int this[int index]
        {
            get
            {
                if ((uint)index >= Count)
                    throw new ArgumentOutOfRangeException(nameof(index));
                return Unsafe.Add(ref x, index);
            }
            set
            {
                if ((uint)index >= Count)
                    throw new ArgumentOutOfRangeException(nameof(index));
                Unsafe.Add(ref x, index) = value;
            }
        }

        public int Count => 2;

        public bool Equals(int2 other)
        {
            return x.Equals(other.x) && y.Equals(other.y);
        }

        public override bool Equals(object obj)
        {
            return obj is int2 other && Equals(other);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                var hash = 17;
                hash = hash * 31 + x.GetHashCode();
                hash = hash * 31 + y.GetHashCode();
                return hash;
            }
        }

        public int CompareTo(int2 other)
        {
            var xComparison = x.CompareTo(other.x);
            if (xComparison != 0) return xComparison;
            var yComparison = y.CompareTo(other.y);
            if (yComparison != 0) return yComparison;
            return 0;
        }

        public override string ToString()
        {
            return FormattableString.Invariant($"{x}, {y}");
        }

        public static int2 Parse(string value)
        {
            value = value.Trim();
            if (value.Length >= 2 && value[0] == '[' && value[value.Length - 1] == ']')
                value = value.Substring(1, value.Length - 2);
            var values = value.Split(',');
            if (values.Length != 2)
                throw new FormatException("Expected 2 vector components.");
            return new(int.Parse(values[0].Trim(), System.Globalization.CultureInfo.InvariantCulture), int.Parse(values[1].Trim(), System.Globalization.CultureInfo.InvariantCulture));
        }

        public static int2 Parse(string value, IFormatProvider format)
        {
            value = value.Trim();
            if (value.Length >= 2 && value[0] == '[' && value[value.Length - 1] == ']')
                value = value.Substring(1, value.Length - 2);
            var values = value.Split(',');
            if (values.Length != 2)
                throw new FormatException("Expected 2 vector components.");
            return new(int.Parse(values[0].Trim(), format), int.Parse(values[1].Trim(), format));
        }
    }
}
