// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct int2
    {

        public static int Dot(int2 a, int2 b)
        {
            return a.x * b.x + a.y * b.y;
        }

        public static int SqrLength(int2 value)
        {
            return value.x * value.x + value.y * value.y;
        }
    }
}
