// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace KibiHex
{
    public partial struct int3
    {

        public static int Dot(int3 a, int3 b)
        {
            return a.x * b.x + a.y * b.y + a.z * b.z;
        }

        public static int SqrLength(int3 value)
        {
            return value.x * value.x + value.y * value.y + value.z * value.z;
        }
    }
}
