// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace DVG.Maths
{
    public partial struct int4
    {

        public static int4 Select(int4 falseValue, int4 trueValue, bool4 mask)
        {
            return new(mask.x ? trueValue.x : falseValue.x, mask.y ? trueValue.y : falseValue.y, mask.z ? trueValue.z : falseValue.z, mask.w ? trueValue.w : falseValue.w);
        }

        public static int4 Select(int4 falseValue, int4 trueValue, bool mask)
        {
            return new(mask ? trueValue.x : falseValue.x, mask ? trueValue.y : falseValue.y, mask ? trueValue.z : falseValue.z, mask ? trueValue.w : falseValue.w);
        }

        public static int4 Select(int falseValue, int trueValue, bool4 mask)
        {
            return new(mask.x ? trueValue : falseValue, mask.y ? trueValue : falseValue, mask.z ? trueValue : falseValue, mask.w ? trueValue : falseValue);
        }

        public static bool4 Equal(int4 a, int4 b)
        {
            return new(a.x == b.x, a.y == b.y, a.z == b.z, a.w == b.w);
        }

        public static bool4 Equal(int4 a, int b)
        {
            return new(a.x == b, a.y == b, a.z == b, a.w == b);
        }

        public static bool4 Equal(int a, int4 b)
        {
            return new(a == b.x, a == b.y, a == b.z, a == b.w);
        }

        public static bool4 NotEqual(int4 a, int4 b)
        {
            return new(a.x != b.x, a.y != b.y, a.z != b.z, a.w != b.w);
        }

        public static bool4 NotEqual(int4 a, int b)
        {
            return new(a.x != b, a.y != b, a.z != b, a.w != b);
        }

        public static bool4 NotEqual(int a, int4 b)
        {
            return new(a != b.x, a != b.y, a != b.z, a != b.w);
        }

        public static bool4 LessThan(int4 a, int4 b)
        {
            return new(a.x < b.x, a.y < b.y, a.z < b.z, a.w < b.w);
        }

        public static bool4 LessThan(int4 a, int b)
        {
            return new(a.x < b, a.y < b, a.z < b, a.w < b);
        }

        public static bool4 LessThan(int a, int4 b)
        {
            return new(a < b.x, a < b.y, a < b.z, a < b.w);
        }

        public static bool4 LessThanOrEqual(int4 a, int4 b)
        {
            return new(a.x <= b.x, a.y <= b.y, a.z <= b.z, a.w <= b.w);
        }

        public static bool4 LessThanOrEqual(int4 a, int b)
        {
            return new(a.x <= b, a.y <= b, a.z <= b, a.w <= b);
        }

        public static bool4 LessThanOrEqual(int a, int4 b)
        {
            return new(a <= b.x, a <= b.y, a <= b.z, a <= b.w);
        }

        public static bool4 GreaterThan(int4 a, int4 b)
        {
            return new(a.x > b.x, a.y > b.y, a.z > b.z, a.w > b.w);
        }

        public static bool4 GreaterThan(int4 a, int b)
        {
            return new(a.x > b, a.y > b, a.z > b, a.w > b);
        }

        public static bool4 GreaterThan(int a, int4 b)
        {
            return new(a > b.x, a > b.y, a > b.z, a > b.w);
        }

        public static bool4 GreaterThanOrEqual(int4 a, int4 b)
        {
            return new(a.x >= b.x, a.y >= b.y, a.z >= b.z, a.w >= b.w);
        }

        public static bool4 GreaterThanOrEqual(int4 a, int b)
        {
            return new(a.x >= b, a.y >= b, a.z >= b, a.w >= b);
        }

        public static bool4 GreaterThanOrEqual(int a, int4 b)
        {
            return new(a >= b.x, a >= b.y, a >= b.z, a >= b.w);
        }
    }
}
