// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct quaternion
    {

        public static quaternion CreateFromAxisAngle(float3 axis, float angle)
        {
            var normalizedAxis = float3.NormalizeSafe(axis);
            var halfAngle = angle * 0.5f;
            var sine = Maths.Sin(halfAngle);
            return new quaternion(-normalizedAxis.x * sine, -normalizedAxis.y * sine, -normalizedAxis.z * sine, Maths.Cos(halfAngle));
        }

        public static quaternion CreateFromYawPitchRoll(float yaw, float pitch, float roll)
        {
            var halfRoll = roll * 0.5f;
            var halfPitch = pitch * 0.5f;
            var halfYaw = yaw * 0.5f;
            var sinRoll = Maths.Sin(halfRoll);
            var cosRoll = Maths.Cos(halfRoll);
            var sinPitch = Maths.Sin(halfPitch);
            var cosPitch = Maths.Cos(halfPitch);
            var sinYaw = Maths.Sin(halfYaw);
            var cosYaw = Maths.Cos(halfYaw);
            return new quaternion(
                -(cosYaw * sinPitch * cosRoll + sinYaw * cosPitch * sinRoll),
                -(sinYaw * cosPitch * cosRoll - cosYaw * sinPitch * sinRoll),
                -(cosYaw * cosPitch * sinRoll - sinYaw * sinPitch * cosRoll),
                cosYaw * cosPitch * cosRoll + sinYaw * sinPitch * sinRoll);
        }

        public static float3 Rotate(quaternion rotation, float3 value)
        {
            var qv = new float3(rotation.x, rotation.y, rotation.z);
            var t = 2f * float3.Cross(qv, value);
            return value + rotation.w * t + float3.Cross(qv, t);
        }

        public static quaternion CreateFromRotationMatrix(float4x4 matrix)
        {
            var trace = matrix.M11 + matrix.M22 + matrix.M33;
            if (trace > 0f) { var s = Maths.Sqrt(trace + 1f) * 2f; return new quaternion((matrix.M32 - matrix.M23) / s, (matrix.M13 - matrix.M31) / s, (matrix.M21 - matrix.M12) / s, 0.25f * s); }
            if (matrix.M11 > matrix.M22 && matrix.M11 > matrix.M33) { var s = Maths.Sqrt(1f + matrix.M11 - matrix.M22 - matrix.M33) * 2f; return new quaternion(0.25f * s, (matrix.M12 + matrix.M21) / s, (matrix.M13 + matrix.M31) / s, (matrix.M32 - matrix.M23) / s); }
            if (matrix.M22 > matrix.M33) { var s = Maths.Sqrt(1f + matrix.M22 - matrix.M11 - matrix.M33) * 2f; return new quaternion((matrix.M12 + matrix.M21) / s, 0.25f * s, (matrix.M23 + matrix.M32) / s, (matrix.M13 - matrix.M31) / s); }
            { var s = Maths.Sqrt(1f + matrix.M33 - matrix.M11 - matrix.M22) * 2f; return new quaternion((matrix.M13 + matrix.M31) / s, (matrix.M23 + matrix.M32) / s, 0.25f * s, (matrix.M21 - matrix.M12) / s); }
        }

        public static float4x4 ToRotationMatrix(quaternion rotation)
        {
            return float4x4.CreateFromQuaternion(rotation);
        }

        public static void ToAxisAngle(quaternion rotation, out float3 axis, out float angle)
        {
            var normalized = NormalizeSafe(rotation);
            angle = 2f * Maths.Acos(Maths.Clamp(normalized.w, -1f, 1f));
            var scale = Maths.Sqrt(Maths.Max(1e-20f, 1f - normalized.w * normalized.w));
            axis = scale <= 1e-10f ? new float3(1f, 0f, 0f) : new float3(-normalized.x / scale, -normalized.y / scale, -normalized.z / scale);
        }
    }
}
