// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct quaternion
    {

        public static float Dot(quaternion left, quaternion right)
        {
            return left.x * right.x + left.y * right.y + left.z * right.z + left.w * right.w;
        }

        public static float LengthSquared(quaternion value)
        {
            return Dot(value, value);
        }

        public static quaternion Normalize(quaternion value)
        {
            return value / Maths.Sqrt(LengthSquared(value));
        }

        public static quaternion NormalizeSafe(quaternion value)
        {
            var lengthSquared = LengthSquared(value);
            return lengthSquared <= 1e-20f ? identity : value / Maths.Sqrt(lengthSquared);
        }

        public static quaternion Conjugate(quaternion value)
        {
            return new quaternion(-value.x, -value.y, -value.z, value.w);
        }

        public static bool TryInverse(quaternion value, out quaternion result)
        {
            var lengthSquared = LengthSquared(value);
            if (lengthSquared <= 1e-20f) { result = default; return false; }
            result = Conjugate(value) / lengthSquared;
            return true;
        }

        public static quaternion Inverse(quaternion value)
        {
            return TryInverse(value, out var result) ? result : identity;
        }

        public static quaternion Lerp(quaternion start, quaternion end, float amount)
        {
            if (Dot(start, end) < 0f) end = -end;
            return NormalizeSafe(start + (end - start) * amount);
        }

        public static quaternion Slerp(quaternion start, quaternion end, float amount)
        {
            var dot = Dot(start, end);
            if (dot < 0f) { end = -end; dot = -dot; }
            if (dot > 0.9995f) return Lerp(start, end, amount);
            dot = Maths.Clamp(dot, -1f, 1f);
            var angle = Maths.Acos(dot);
            var scale = 1f / Maths.Sin(angle);
            return start * (Maths.Sin((1f - amount) * angle) * scale) + end * (Maths.Sin(amount * angle) * scale);
        }
    }
}
