// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    /// <summary>A left-handed quaternion stored as (x, y, z, w).</summary>
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    [System.Runtime.Serialization.DataContract]
    public partial struct quaternion : IEquatable<quaternion>
    {

        public float x;

        public float y;

        public float z;

        public float w;

        /// <summary>The identity rotation.</summary>
        public static readonly quaternion identity = new quaternion(0f, 0f, 0f, 1f);

        public quaternion(float x, float y, float z, float w)
        {
            this.x = x;
            this.y = y;
            this.z = z;
            this.w = w;
        }

        public quaternion(float4 value)
        {
            x = value.x;
            y = value.y;
            z = value.z;
            w = value.w;
        }

        public static quaternion Identity => identity;

        public float X
        {
            get => x;
            set => x = value;
        }

        public float Y
        {
            get => y;
            set => y = value;
        }

        public float Z
        {
            get => z;
            set => z = value;
        }

        public float W
        {
            get => w;
            set => w = value;
        }

        public bool Equals(quaternion other)
        {
            return this == other;
        }

        public override bool Equals(object obj)
        {
            return obj is quaternion other && Equals(other);
        }

        public override int GetHashCode()
        {
            unchecked { var hash = 17; hash = hash * 31 + x.GetHashCode(); hash = hash * 31 + y.GetHashCode(); hash = hash * 31 + z.GetHashCode(); hash = hash * 31 + w.GetHashCode(); return hash; }
        }

        public override string ToString()
        {
            return FormattableString.Invariant($"({x}, {y}, {z}, {w})");
        }
    }
}
