// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct uint3
    {

        public static uint3 Select(uint3 falseValue, uint3 trueValue, bool3 mask)
        {
            return new(mask.x ? trueValue.x : falseValue.x, mask.y ? trueValue.y : falseValue.y, mask.z ? trueValue.z : falseValue.z);
        }

        public static uint3 Select(uint3 falseValue, uint3 trueValue, bool mask)
        {
            return new(mask ? trueValue.x : falseValue.x, mask ? trueValue.y : falseValue.y, mask ? trueValue.z : falseValue.z);
        }

        public static uint3 Select(uint falseValue, uint trueValue, bool3 mask)
        {
            return new(mask.x ? trueValue : falseValue, mask.y ? trueValue : falseValue, mask.z ? trueValue : falseValue);
        }

        public static bool3 Equal(uint3 a, uint3 b)
        {
            return new(a.x == b.x, a.y == b.y, a.z == b.z);
        }

        public static bool3 Equal(uint3 a, uint b)
        {
            return new(a.x == b, a.y == b, a.z == b);
        }

        public static bool3 Equal(uint a, uint3 b)
        {
            return new(a == b.x, a == b.y, a == b.z);
        }

        public static bool3 NotEqual(uint3 a, uint3 b)
        {
            return new(a.x != b.x, a.y != b.y, a.z != b.z);
        }

        public static bool3 NotEqual(uint3 a, uint b)
        {
            return new(a.x != b, a.y != b, a.z != b);
        }

        public static bool3 NotEqual(uint a, uint3 b)
        {
            return new(a != b.x, a != b.y, a != b.z);
        }

        public static bool3 LessThan(uint3 a, uint3 b)
        {
            return new(a.x < b.x, a.y < b.y, a.z < b.z);
        }

        public static bool3 LessThan(uint3 a, uint b)
        {
            return new(a.x < b, a.y < b, a.z < b);
        }

        public static bool3 LessThan(uint a, uint3 b)
        {
            return new(a < b.x, a < b.y, a < b.z);
        }

        public static bool3 LessThanOrEqual(uint3 a, uint3 b)
        {
            return new(a.x <= b.x, a.y <= b.y, a.z <= b.z);
        }

        public static bool3 LessThanOrEqual(uint3 a, uint b)
        {
            return new(a.x <= b, a.y <= b, a.z <= b);
        }

        public static bool3 LessThanOrEqual(uint a, uint3 b)
        {
            return new(a <= b.x, a <= b.y, a <= b.z);
        }

        public static bool3 GreaterThan(uint3 a, uint3 b)
        {
            return new(a.x > b.x, a.y > b.y, a.z > b.z);
        }

        public static bool3 GreaterThan(uint3 a, uint b)
        {
            return new(a.x > b, a.y > b, a.z > b);
        }

        public static bool3 GreaterThan(uint a, uint3 b)
        {
            return new(a > b.x, a > b.y, a > b.z);
        }

        public static bool3 GreaterThanOrEqual(uint3 a, uint3 b)
        {
            return new(a.x >= b.x, a.y >= b.y, a.z >= b.z);
        }

        public static bool3 GreaterThanOrEqual(uint3 a, uint b)
        {
            return new(a.x >= b, a.y >= b, a.z >= b);
        }

        public static bool3 GreaterThanOrEqual(uint a, uint3 b)
        {
            return new(a >= b.x, a >= b.y, a >= b.z);
        }
    }
}
