// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace KibiHex
{
    public partial struct uint2
    {

        public static uint2 Select(uint2 falseValue, uint2 trueValue, bool2 mask)
        {
            return new(mask.x ? trueValue.x : falseValue.x, mask.y ? trueValue.y : falseValue.y);
        }

        public static uint2 Select(uint2 falseValue, uint2 trueValue, bool mask)
        {
            return new(mask ? trueValue.x : falseValue.x, mask ? trueValue.y : falseValue.y);
        }

        public static uint2 Select(uint falseValue, uint trueValue, bool2 mask)
        {
            return new(mask.x ? trueValue : falseValue, mask.y ? trueValue : falseValue);
        }

        public static bool2 Equal(uint2 a, uint2 b)
        {
            return new(a.x == b.x, a.y == b.y);
        }

        public static bool2 Equal(uint2 a, uint b)
        {
            return new(a.x == b, a.y == b);
        }

        public static bool2 Equal(uint a, uint2 b)
        {
            return new(a == b.x, a == b.y);
        }

        public static bool2 NotEqual(uint2 a, uint2 b)
        {
            return new(a.x != b.x, a.y != b.y);
        }

        public static bool2 NotEqual(uint2 a, uint b)
        {
            return new(a.x != b, a.y != b);
        }

        public static bool2 NotEqual(uint a, uint2 b)
        {
            return new(a != b.x, a != b.y);
        }

        public static bool2 LessThan(uint2 a, uint2 b)
        {
            return new(a.x < b.x, a.y < b.y);
        }

        public static bool2 LessThan(uint2 a, uint b)
        {
            return new(a.x < b, a.y < b);
        }

        public static bool2 LessThan(uint a, uint2 b)
        {
            return new(a < b.x, a < b.y);
        }

        public static bool2 LessThanOrEqual(uint2 a, uint2 b)
        {
            return new(a.x <= b.x, a.y <= b.y);
        }

        public static bool2 LessThanOrEqual(uint2 a, uint b)
        {
            return new(a.x <= b, a.y <= b);
        }

        public static bool2 LessThanOrEqual(uint a, uint2 b)
        {
            return new(a <= b.x, a <= b.y);
        }

        public static bool2 GreaterThan(uint2 a, uint2 b)
        {
            return new(a.x > b.x, a.y > b.y);
        }

        public static bool2 GreaterThan(uint2 a, uint b)
        {
            return new(a.x > b, a.y > b);
        }

        public static bool2 GreaterThan(uint a, uint2 b)
        {
            return new(a > b.x, a > b.y);
        }

        public static bool2 GreaterThanOrEqual(uint2 a, uint2 b)
        {
            return new(a.x >= b.x, a.y >= b.y);
        }

        public static bool2 GreaterThanOrEqual(uint2 a, uint b)
        {
            return new(a.x >= b, a.y >= b);
        }

        public static bool2 GreaterThanOrEqual(uint a, uint2 b)
        {
            return new(a >= b.x, a >= b.y);
        }
    }
}
