// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct uint3
    {

        public static uint Dot(uint3 a, uint3 b)
        {
            return a.x * b.x + a.y * b.y + a.z * b.z;
        }

        public static uint SqrLength(uint3 value)
        {
            return value.x * value.x + value.y * value.y + value.z * value.z;
        }
    }
}
