// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace Delta.Maths
{
    public partial struct uint3
    {

        public static uint3 Min(uint3 a, uint3 b)
        {
            return new(Maths.Min(a.x, b.x), Maths.Min(a.y, b.y), Maths.Min(a.z, b.z));
        }

        public static uint3 Min(uint3 a, uint b)
        {
            return new(Maths.Min(a.x, b), Maths.Min(a.y, b), Maths.Min(a.z, b));
        }

        public static uint3 Min(uint a, uint3 b)
        {
            return new(Maths.Min(a, b.x), Maths.Min(a, b.y), Maths.Min(a, b.z));
        }

        public static uint3 Max(uint3 a, uint3 b)
        {
            return new(Maths.Max(a.x, b.x), Maths.Max(a.y, b.y), Maths.Max(a.z, b.z));
        }

        public static uint3 Max(uint3 a, uint b)
        {
            return new(Maths.Max(a.x, b), Maths.Max(a.y, b), Maths.Max(a.z, b));
        }

        public static uint3 Max(uint a, uint3 b)
        {
            return new(Maths.Max(a, b.x), Maths.Max(a, b.y), Maths.Max(a, b.z));
        }

        public static uint3 Clamp(uint3 value, uint min, uint max)
        {
            return new(Maths.Clamp(value.x, min, max), Maths.Clamp(value.y, min, max), Maths.Clamp(value.z, min, max));
        }

        public static uint3 Clamp(uint3 value, uint3 min, uint3 max)
        {
            return new(Maths.Clamp(value.x, min.x, max.x), Maths.Clamp(value.y, min.y, max.y), Maths.Clamp(value.z, min.z, max.z));
        }

        public static uint Sum(uint3 value)
        {
            return value.x + value.y + value.z;
        }
    }
}
