// <auto-generated />
#nullable enable
using System;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

namespace DVG.Maths
{
    public partial struct uint2
    {

        public static uint Dot(uint2 a, uint2 b)
        {
            return a.x * b.x + a.y * b.y;
        }

        public static uint SqrLength(uint2 value)
        {
            return value.x * value.x + value.y * value.y;
        }
    }
}
